heartcombo/devise

- lib/devise/test_helpers.rb
- test/test_helpers_test.rb
The `#warden` method in the `Devise::TestHelpers` module adds a Warden proxy object to the request environment hash under the 'warden' key. Including this module in your test case registers that method as a callback, which runs before every test: https://github.com/plataformatec/devise/blob/v3.4.1/lib/devise/test_helpers.rb#L12
The request object itself is created in a callback added by Rails: https://github.com/rails/rails/blob/v4.2.0/actionpack/lib/action_controller/test_case.rb#L687
So before each test runs, the Rails callback creates the request object, and then the Devise callback adds a Warden proxy object to it.
I was using the [rspec-retry](https://github.com/y310/rspec-retry) gem, and noticed that my controller specs would always fail whenever they were retried with this error: …
> Allow warden proxy to change with request in tests

- lib/devise/rails.rb
- test/rails_test.rb
It is obvious that this initializer should be executed before Rails build_middleware_stack as Omniauth is build on middleware.
Also it is obvious that we need that initializer to be executed after all config/initializers/* files (that is where devise.rb usually is).
> Added devise.omniauth initializer explicit position requirements.

- app/controllers/devise_controller.rb
This should still keep the devise lookup in the case that a customed scope is not passed as option, but if instead the custom scope is passed, then the find_message method will use it.
This is kind of useful, if i don't want overwrite the devise locale, and use different locale files, but keeping still the fallback of my devise locale.
> Update find_message to accept scope

- lib/devise/models/trackable.rb
This reverts commit 43d0715238e762e89cc465a441dd1bdffc0529e3.
save() returns false only when validations failed. In this case, validations are not performed. Therefore save() may never return a falsy value. If save() fails, the appropriate exception is raised.
With certain ORMs, such as NoBrainer, save() never returns true/false, but always raise an exception. This commit lift the incompatiblity.
Note: Nowhere in the current codebase, `save(validate: false)` is checked.
Fixes https://github.com/nviennot/devise-nobrainer/issues/2
> Revert "Better error message in case a trackable module can't be saved."

- test/rails_app/config/environments/production.rb
apply the same change to production.rb that was put into test.rb to get rid of the deprecation warning related to the config.serve_static_assets -> config.serve_static_files in Rails 4.2.0
> get rid of config.serve_static_assets deprecation warning from production.rb

- lib/devise/models/confirmable.rb
- test/models/confirmable_test.rb
Removes line setting token to nil as mentioned in https://github.com/plataformatec/devise/issues/3429.
By saving it, a message (self.errors.add(:email, :already_confirmed)) can be shown to the user. If set to nil, the potentially misleading message "Confirmation token is invalid" is given. In such a case, if the user does not log in, they may never know that their account's email has already been confirmed.
Test cases: 1 added (checks for :already_confirmed error), 1 removed (checks token set to nil), 3 changed.
> Keep used confirmation tokens for more user friendly error message (issue #3429)

- lib/devise/models/database_authenticatable.rb
Due to bug in Ruby 2.2.0; The bug has been acknowledged and fixed in trunk (https://github.com/ruby/ruby/commit/622f3f14b6928ee4fe3afa96db0250eb9da32e7a)
When password comes in FormEncoded the result of `gsub` breaks when peppered with `nil`.
This only adds pepper if defined on the model and works around this bug.
This fixes #3415
To reproduce: https://gist.github.com/davestevens/a9187de713a32cb005b1
> Only add pepper if needed

- CHANGELOG.md
- app/controllers/devise/confirmations_controller.rb
- app/controllers/devise/omniauth_callbacks_controller.rb
- app/controllers/devise/passwords_controller.rb
- app/controllers/devise/registrations_controller.rb
- app/controllers/devise/sessions_controller.rb
- app/controllers/devise/unlocks_controller.rb
- app/controllers/devise_controller.rb
- test/controllers/inherited_controller_i18n_messages_test.rb
closes #3367
I will now start working in the tests but you can already review the changes. I've tested it with my application manually already.
> Use Devise translations when inheriting from core controllers

- README.md
- lib/generators/active_record/templates/migration.rb
- lib/generators/active_record/templates/migration_existing.rb
removing warning from gererated migrations
```
DEPRECATION WARNING: `#timestamp` was called without specifying an option for `null`. In Rails 5, this behavior will change to `null: false`. You should manually specify `null: true` to prevent the behavior of your existing migrations from changing. (called from block in change at /Users/luciano/Dropbox/projects/Luciano-Sousa/db/migrate/20150203012635_devise_create_users.rb:36)
```
> removing deprecation warning from rails 5

- lib/generators/templates/devise.rb
Adding a couple comments in initializer that explain that Devise will use `secret_key_base` on Rails 4+ applications as its `secret_key` by default.
> Add comments re: secret_key on Rails 4+ apps

- lib/devise/failure_app.rb
I have an app which uses `devise` and `activeadmin` (which uses `devise` too).
I needed to customize `route` depending on the scope - redirecting to `new_user_registration_url` when user accesses the app itself and redirecting to `new_admin_user_session` when accessing admin panel.
Without this change it was even impossible to access login page of admin panel (even having `config.skip_before_filter :authenticate_user!` in `activeadmin` initializer).
> Extracted route to separate method to be able to override in child class

- README.md
Rails now defaults to `config.log_level = :debug` in production. Since the entire contents of outgoing emails are logged at the debug level, this means plaintext password reset tokens are exposed in log files. Active Job also logs all arguments to enqueued jobs at the info level, so `deliver_later` will leak tokens as well, even if the log level is set to `:info`.
I suggest updating the Devise README to make developers aware of the issue.
> Add warning about logged tokens to the README

- lib/devise/failure_app.rb
By Using devise on mountable Engines with Rails 4.2, the scope_url method from FailureApp will return a wrong url/path. Concrete in this line: https://github.com/plataformatec/devise/blob/a93edc72fd9f6cc5839dd74107b215a81c16dc37/lib/devise/failure_app.rb#L119
By setting the script_name option to nil, it overrides the engine's prefix set on the routes.rb from the main_app. Example:
````ruby
Rails.application.routes.draw do
mount Admin::Engine, at: 'admin'
end
`````
However until Rails 4.1 the returned path was correct. After this commit: https://github.com/rails/rails/commit/33d6e3be623d4dbcec077e62699272cbdcd23f37 by overriding the script_name option (it should be the engine_name), action_dispatch returns the path without the engine prefix and this ist wrong
In FailureApp this condition …
> workaround for mountable Engines with Rails 4.2

- app/views/devise/confirmations/new.html.erb
Ref. bug/issue: https://github.com/plataformatec/devise/issues/3457
If the user does not click the confirmation link within the confirm_within time period, he is taken to a resend confirmation page. On that page, actually the old email address is shown, and not the new one.
It is a potential security risk, since it will leak the user's old email address to any new user that might have gotten the confirmation email when the original user was trying to change his email (and did a typo).
`:autofocus` removed, and `:readonly` added, since the user shouldn't be able to change the confirmation email address, when asking for a new confirmation email. Allowing the user to change the email address is a another potential security risk:
- A malicious user getting hold of an old confirmation link …
> Fix potential security leak in email reconfirmation flow

- lib/devise/models/authenticatable.rb
I'm using Devise 3.2.3 + Mongoid 4.0.0.beta1 and when I try to call `current_user` I get:
~~~
The operation: #<Moped::Protocol::Query
@length=125
@request_id=18
@response_to=0
@op_code=2004
@flags=[]
@full_collection_name="orodruin_development.users"
@skip=0
@limit=-1
@selector={"$query"=>{"_id"=>{"$oid"=>BSON::ObjectId('530a1ec84e49550fbd000000')}}, "$orderby"=>{:_id=>1}}
@fields=nil>
failed with error 10068: "invalid operator: $oid"
See https://github.com/mongodb/mongo/blob/master/docs/errors.md
for details about this error.
~~~
Bug is somewhere where this is set:
warden.user.user.key: [[{"$oid"=>BSON::ObjectId('530a1ec84e49550fbd000000')}], "$2a$10$/J1DMorvMdGZm6aQicsYL."]
> Devise + Mongoid store wrong data in session

- lib/devise/models/authenticatable.rb
I am using some Devise modules in a Sinatra app.  Because Devise::Models::Authenticatable expects Rails to be defined, I need to add the following hack:
require 'active_model'
module Rails
VERSION ||= ActiveModel::VERSION # Needed in order to load devise/authenticatable
end
However, while this solves the immediate problem of making it possible to `include Devise::Models::Authenticatable`, it creates a new set of problems--other gems ([annotate](https://github.com/ctran/annotate_models/blob/v2.6.5/lib/annotate.rb#L130) and recent versions of [paperclip](https://github.com/thoughtbot/paperclip/issues/1739), [delayed_job](https://github.com/collectiveidea/delayed_job/pull/634) and [ActiveRecord](https://github.com/rails/rails/blob/v4.2.0/activerecord/lib/active_record/connection_handling.rb#L …
> allow Devise::Models::Authenticatable to be loaded before Rails

- app/controllers/devise_controller.rb
- test/controllers/internal_helpers_test.rb
Rails 5 will [not have `hide_action` any longer](https://github.com/rails/rails/pull/18371/files), as the Rails convention is to not expose private or protected methods as actions, thus obviating the need for `hide_action`.
Presumably, there is code inheriting from `DeviseController` that is calling these helpers, so they cannot be private, so `protected` seems to be the only way to get Devise working with Rails 5.  At least to me :)
I also considered back-porting `hide_action` into this gem, but that felt like the wrong way to go.
> remove use of hide_action in favor of protected

- lib/devise/models/rememberable.rb
`remember_expired?` already calls this method
> Remove redundant `remember_created_at.nil?`

- lib/devise/mapping.rb
- test/mapping_test.rb
Introspecting the scope of an object can make it difficult to use
wrapper patterns. See issue plataformatec/devise#3307 for an example.
Allow objects to specify their scope explicitly by implementing
`devise_scope`.
> Allow objects to specify their devise scope.

- lib/devise/strategies/authenticatable.rb
- lib/devise/strategies/database_authenticatable.rb
In order to be more clear about the expectations of for authenticating, we use `password.present?` so there is no confusion about the role of the `valid_password?` method.
Also, this adds some documentation to the `valid_password?` method clarify its functionality.
More info: #3519
> Valid password

- lib/devise/rails/routes.rb
Documentation only update - Rails 4.2 deprecates specifying controller without an action as 'to' parameter in routes. I just updated the docs to suggest the same thing that code below does. Please see:  #3560
> improve error message when using omniauth callbacks under a dynamic segment

- lib/devise/encryptor.rb
- lib/devise/models/database_authenticatable.rb
- test/devise_test.rb
This logic is generic and reusable -- hash a secret; and take an unhashed secret and compare it to a hashed secret. This breaks this out to make it reusable in other places. Specifically, we use this in our own token auth at Bonobos that we plan to split out as a Devise extension. This will make that possible without copy & pasting this code.
> Split out BCrypt hashing to make it reusable

- lib/devise/controllers/url_helpers.rb
I'm not hugely familiar with ruby internals vis-a-vis sclass semantics,
but this *probably* serves as a workaround for the MRI thread-safety
bug mentioned in #3505.
Beyond that, and even if this doesn't fix the thread-safety issue, per
[this blog post][1], `define_method` is recommended over `class_eval`
for performance (and, fwiw, readability) reasons anyway.
[1]: http://tenderlovemaking.com/2013/03/03/dynamic_method_definitions.html
> Use `define_method`, not `class_eval`, for url_helpers

- lib/devise.rb
By default, length is 15 characters
> Allow the user to set the length of friendly token

- lib/devise/failure_app.rb
- test/failure_app_test.rb
`Devise.available_router_name` currently returns either
`Devise.router_name` or `:main_app`. As such, any redirecting is done
within either of those contexts. Which leads to undesirable redirects
for scopes that reside in an `isolate_namespace` mounted engine.
This commit makes it possible for FailureApp’s redirect behavior to be
performed in the context of the `router_name` given to `devise_for`.
Test case added to cover undesirable behavior. Without change to
`lib/devise/failure_app.rb`, test case throws exception.
> Use router_name from scope if available

- lib/generators/templates/controllers/README
When creating devise controllers there is a message presented:
Some setup you must do manually if you haven't yet:
Ensure you have overridden routes for generated controllers in your route.rb.
For example:
Rails.application.routes.draw do
devise_for :users, controllers: {
sessions: 'users/sessions'
}
end
However, the file "Route.rb" should be "Routes.rb"
> fixed typo referring to routes.rb file

- lib/devise/controllers/sign_in_out.rb
This method is same to `expire_data_after_sign_in!`,
so alias it
> Refactoring `expire_data_after_sign_out!`

- lib/devise.rb
- lib/devise/models/database_authenticatable.rb
Spring started complaining about Devise::Encryptor being uninitialized so I figured that it should be autoloaded.
> Autoload Encryptor

- devise.gemspec
rubyforge_project option is deprecated.
Thank you!
> Remove rubyforge_project option

- lib/devise.rb
- test/devise_test.rb
The current email_regexp allows non-word characters at the end: http://rubular.com/r/nzwZ3SXJGo
This small change to the regex will fix that: http://rubular.com/r/jyE5N8FtSM
> Fix default email_regexp config to disallow trailing non-word characters

- app/controllers/devise/passwords_controller.rb
As discussed in #3668, this PR makes `after_resetting_password_path_for(resource)` to take effect when `sign_in_after_reset_password` is disabled.
> redirect to after_resetting_password_path always

- Gemfile.lock
- lib/devise.rb
- lib/devise/hooks/timeoutable.rb
- lib/generators/templates/devise.rb
- test/integration/timeoutable_test.rb
- test/rails_app/app/controllers/admins_controller.rb
- test/rails_app/config/routes.rb
Hi!
I was going to add `timeoutable` to my app so I had a look at the config and saw `expire_auth_token_on_timeout`. So asked myself "what is this?" and "do I need it?". I had a look at the code and saw it calls the `reset_authentication_token!` method that it's not defined anywhere. Then I did a bit of git digging and I think all of this was probably meant to be removed together with dff7891.
Regards and thanks for this gem!
> Remove obsolete unused `expire_auth_token_on_timeout` config

- lib/devise/models/confirmable.rb
- test/mailers/confirmation_instructions_test.rb
- test/models/confirmable_test.rb
Addresses https://github.com/plataformatec/devise/issues/3640.
I did this by changing as little code as possible. It's definitely possible to strip out `raw_confirmation_token` entirely, but you'd have to change a LOT of specs. Please advise if this is up to par for your repository.
> Do not use digests for confirmation tokens

- README.md
Made minor grammar improvements in the readme file.
1) Line 198: changed the form of the verb `allow` from `allows` to `allow` (plural form instead of singular).
2) Line 352: the unnecessary usage of `to`. While being grammatically correct, the sentence sounds more natural without `to` (besides, the variant without `to` is more frequently used in English).
> Improve grammar on lines 189 and 352 in readme

- app/views/devise/passwords/edit.html.erb
Style fix for https://github.com/plataformatec/devise/issues/3698
Edit password view before (without using the Validatable module): 
Edit password view after:
> Remove unnecessary line break on edit password page.

- lib/devise/strategies/authenticatable.rb
Allow basic authentication to be case insensitive as per the HTTP 1.1 spec [RFC 2068](http://www.rfc-base.org/txt/rfc-2068.txt) Section 11
> It uses an extensible, case-insensitive token to identify the authentication scheme, followed by a comma-separated list of attribute-value pairs which carry the parameters necessary for achieving authentication via that scheme.
We have a particular client in production that has basic auth hard-coded as `basic` rather than `Basic` and devise is rejecting perfectly fine credentials. Making this small change has allowed us to authenticate this client with no issues. 
If we can get this accepted upstream then we can stop patching devise whenever we deploy our rails apps.
> Basic auth case insensitive pattern match

- lib/devise.rb
The existing comment seems to be either outdated or obscure. I interpret it as meaning that configure_warden! is invoked by an 'initializer' block in class Devise::Engine, i.e. in lib/devise/rails.rb. However, as far as I can tell the only time the method is invoked is when ActionDispatch::Routing::RouteSet#finalize! is called, and this is aliased by devise to finalize_with_devise!.
> Update comment on Devise.configure_warden

- lib/devise/failure_app.rb
URLs are now generated using the configured `Devise.parent_controller`, not the hardcoded `ApplicationController`, as in the rest of the library.
Also it now uses the instance method as recommended to implement in the Rails guides, not only the class-level hash. 
Only thing I wasn't sure of is how to test this. I couldn't find a test for the old implementation but when I tried implementing one, I couldn't find a way to modify the environment in a way that changed the parent controller without leaving a big mess behind. Changing `Devise.parent_controller` or modifying `ApplicationWithFakeEngine` has no effect at the time the tests are run as all classes and hierarchy have already been set up.
I don't like contributing code w/o tests so I'm open to suggestions and will amend my code …
> Use default_url_options from parent_controller

- lib/devise.rb
The existing comment suggests that add_module is used only for modules that are not provided by Devise itself.
> Update comment on Devise.add_module

- lib/generators/templates/markerb/confirmation_instructions.markerb
- lib/generators/templates/markerb/reset_password_instructions.markerb
- lib/generators/templates/markerb/unlock_instructions.markerb
Seeing as the point of the markerb templates is to allow markdown templates to be used for both html and text emails, it makes sense that the links used in said template should be markdown links, not html ones.
This will make no difference to HTML viewers of the email, but should make the view better for text viewers of the email.
> modifys markerb templates to use markdown links, not html ones.

- app/views/devise/shared/_links.html.erb
- test/integration/omniauthable_test.rb
This will display the provider names with the original camelization:
```
facebook => Facebook
github => GitHub
linkedin => LinkedIn
```
We do the same already in the [`OmniauthCallbacksController `](https://github.com/plataformatec/devise/blob/master/app/controllers/devise/omniauth_callbacks_controller.rb#L9).
> use OmniAuth::Utils.camelize

- lib/devise/controllers/helpers.rb
- test/controllers/helper_methods_test.rb
Currently `Devise::Controllers::Helpers` depends on `#helper_method`, which is defined inside `AbstractController::Helpers`.  This module is included in `ActionController::Base`, but it is not included by default in `ActionController::Metal`.
`#helper_method` is not essential to the functionality of the methods inside `Devise::Controllers::Helpers`, so this PR wraps all Devise `#helper_method` calls with `respond_to?(:helper_method)` checks.
> Wrap helper_method calls in respond_to?(:helper_method)

- lib/generators/devise/views_generator.rb
This fixes issue #3790.
Example of previous functionality. This basically just doesn't match up with what Devise expects when rendering the views:
```bash
rails g devise AdminUser
rails g devise:views AdminUser # incorrectly generates the folder name
=>      create    app/views/AdminUser/shared
```
When rendering the scoped views, Devise will always look for the underscored and pluralized folder name, so this trips up a few people.
Fixed version:
```bash
rails g devise AdminUser
rails g devise:views AdminUser # correctly underscores and pluralizes the scope
=>      create    app/views/admin_users/shared
```
> Automatically underscore and pluralize scoped views generator

- lib/devise/hooks/timeoutable.rb
- test/integration/timeoutable_test.rb
I was working on a "session timer" functionality in my current project and making requests without changing `last_request_at` was very useful. What do you think?
> Allow skipping the timeoutable hook

- app/controllers/devise/passwords_controller.rb
On the reset password form, if the form is invalid, the `@minimum_password_length` variable is not set. This PR fix that by calling `set_minimum_password_length` in the update method. I can add some tests if needed :)
> set minimum password length on reset failure

- lib/devise/models/confirmable.rb
- test/models/confirmable_test.rb
I've overridden #confirmation_required? in my application so that only certain classes of users require it, and as a result resetting passwords has broken. This small tweak fixes it.
This time with a test.
> Don't error if resource doesn't need confirming

- lib/devise/models/recoverable.rb
- test/models/recoverable_test.rb
If a new user is created with a reset password token, the previous behavior would automatically clear the token even when it were desired for setting the password for the first time.
> Only clear the reset password token if the model has already been persisted

- lib/devise/models/recoverable.rb
- test/models/recoverable_test.rb
- test/rails_app/app/active_record/user_without_email.rb
- test/rails_app/app/mongoid/user_without_email.rb
- test/rails_app/config/routes.rb
- test/rails_app/lib/shared_user_without_email.rb
- test/support/helpers.rb
@josevalim - raising this PR folling the discussions on [this commit](https://github.com/plataformatec/devise/commit/e641b4b7b97159054b7d92fb14df557ac18ae6f4)
The current implementation is opinionated in that the resource should have
an "email" column on it if it is to be recoverable, which isn't
necessarily the case.  For example, developers may decide to pull emails
out into their own model or have some other way of communicating
password resets to their users (e.g. text message)
I'm not sure there's an easy test to put together for this case, as
minitest doesn't make it very easy to stub the "email_changed?" to raise
an error. Happy to look into building another model in the
"test/rails_app" if you want to have this properly tested though? Or for
a nice way to get calls to …
> Allow resources with no email field to be recoverable

- lib/devise/models/recoverable.rb
- test/models/recoverable_test.rb
This solves the issue where a package might do:
```ruby
user = User.new
user.email = 'test@test.com'
token = user.generate_reset_token
user.save
send_reset_email(token)
```
Since the save clears the reset token, the user will receive a stale token that no longer works.
Closes #3774
> Only clear the reset token on an update

- lib/devise/models/recoverable.rb
`reset_password_period_valid?` returns false if rails application works in singapore time zone. 
```
config.reset_password_within = 6.hours
```
```
user.reset_password_sent_at.utc
=> 2015-12-15 06:57:26 UTC
User.reset_password_within.ago
=> Tue, 15 Dec 2015 08:59:57 SGT +08:00
user.reset_password_sent_at.utc >= User.reset_password_within.ago
=> false
```
> Comparing times in UTC 

- lib/devise/models/confirmable.rb
the confirmable.rb module has a before_create method that generates a confirmation token and a before_update method that calls method :postpone_email_change_until_confirmation_and_regenerate_confirmation_token
Apparently, the second method, recognizes that the email changes from empty string to the one specified and triggers true for method email_changed?
> save in after_create hook breaks devise confirmation

- test/models/confirmable_test.rb
Hi!
I would like to start contributing to Devise as a thank you for a great project. 
I've noticed [this](https://github.com/plataformatec/devise/pull/3793) PR. It fixes https://github.com/plataformatec/devise/issues/3787, but has [no tests](https://github.com/plataformatec/devise/pull/3793#issuecomment-156698377). I thought that adding this test could be a good start. So there it is.
> test for save in after_create hook breaks devise confirmation [3787]

- test/integration/authenticatable_test.rb
This removes a test that was added for a Rails 5 behavior which was deemed to be a bug -  fixed here - https://github.com/rails/rails/pull/22564
> Fix Rails 5 test

- Gemfile.lock
- devise.gemspec
- lib/devise/rails.rb
- lib/devise/token_generator.rb
We can now use Active Support implementation directly and let it handle the caching dependency `thread_safe` was replaced by `concurrent` for Rails 5).
> Remove `KeyGenerator` implementation ported from Rails 4.x.

- README.md
- lib/devise.rb
- lib/devise/controllers/helpers.rb
- lib/devise/parameter_sanitizer.rb
- test/parameter_sanitizer_test.rb
We no longer need to support the `BaseSanitizer` implementation for apps without
the Strong Parameters API, and this section is lacking a minimal set of
docs to document the expected behavior besides the `README` section.
An important change here is that `sanitize` now returns a `HashWIthIndifferentAccess` instead of an `ActionController::Parameters` as it doesn't inherits from `Hash` anymore, and our internals rely on it being a `Hash` that we can operate on (This is one of the headaches from supporting Rails 5).
I didn't documented the `for` method as I believe its API to be quite confusing at the moment. It can accept a block that is stored in the Sanitizer instance and it can mutate an existing `Array` and return it. I think we should normalize it and add a new method for customizing …
> Remove `ParametersSanitizer` inheritance.

- lib/generators/templates/controllers/registrations_controller.rb
- lib/generators/templates/controllers/sessions_controller.rb
Hi, just playing around on a new project, and having a poke around HEAD on devise (mainly because I had read the README of HEAD and not 3.5.3, so stuck with what I'd learned about).
Not really too familiar with devise, so not sure if I'm missing something here, but think I may have noticed something you've missed, so here's a PR.
Devise::ParameterSanitizer has a new syntax for permitting additional attributes to a model. This commit updates the generated controllers to reflect that.
> Update controller generator templates for new ParameterSanitizer syntax

- README.md
This is a documentation-only change to the testing section of README.md. 
It clarifies how to include Devise::TestHelpers for :view tests.
It also clarifies that including Devise::TestHelpers during integration tests is a mistake.
Here's why I believe these things are true: https://github.com/plataformatec/devise/issues/3881
> Documentation clarification to README.md

- lib/generators/templates/devise.rb
Most projects I have worked on have had some kind of "BaseMailer" where various shared methods are stored. Most people are not aware of the `parent_mailer` option so have either duplicated code or had modules included. This just adds this option to the default config template so people are aware of it.
> Add parent_mailer to lib/generators/templates/devise.rb

- lib/devise.rb
It would appear that consistency with the indentation used in the top-level Devise module would dictate this formatting change
> Consistent formatting of file arguments to autoload

- lib/devise/controllers/rememberable.rb
- lib/devise/models/rememberable.rb
An alternative API to deal with the `serialize_from_cookie_with_or_without_record` pile of responsibilities. /cc @josevalim
> Refactor `Rememberable#serialized_in_cookie?` to split class/instance API

- lib/devise/models/rememberable.rb
- test/models/rememberable_test.rb
Time objects aren't properly coerced back when using the JSON cookie serialization,
so we need to do it ourselves.
To avoid any new JSON serialization issues, we now store the `generated_at` as
an String with the timestamp seconds + miliseconds in the cookie but still the
previous JSON encoded format.
Thanks to @boblail at https://github.com/plataformatec/devise/pull/3917 for the
initial patch.
> Attempt to coerce the `generated_at` cookie to a `Time` object.

- lib/devise/models/authenticatable.rb
- lib/devise/models/confirmable.rb
- test/controllers/internal_helpers_test.rb
When implementing the rails 5 updates I used ActionController::Parameters#to_unsafe_h in some methods. This changes those instances to explicitly permit expected parameters instead.
> Explicitly permit rather than using to_unsafe_h

- app/controllers/devise_controller.rb
- lib/devise.rb
- lib/devise/controllers/helpers.rb
- lib/devise/mailers/helpers.rb
- lib/devise/models/confirmable.rb
- lib/devise/models/lockable.rb
- lib/devise/rails/routes.rb
- lib/devise/test_helpers.rb
- lib/generators/templates/devise.rb
- test/failure_app_test.rb
- test/mailers/confirmation_instructions_test.rb
- test/mailers/reset_password_instructions_test.rb
- test/mailers/unlock_instructions_test.rb
- test/rails_app/config/initializers/devise.rb
[The verb *set up* is spelled with a space][1].
[1]: http://www.merriam-webster.com/dictionary/set%20up
> Spell verb *set up* with a space

- README.md
I'd like to remove the Hakiri badge from devise's README.
Since we do check in Gemfile and Gemfile.lock for development
and testing purposes (contrary to the popular belief that gems
don't need those files), Hakiri thinks Devise is a Rails app,
instead of a library/gem.
Depending on the Rails version that is locked in Gemfile.lock,
Hakiri will show several CVEs for Rails. But our Travis pipeline
builds against several Rails' branches, all of them updated.
And it is up to the developers using Devise to update
Rails in their apps.
Those warnings (Rails CVEs) don't make sense for devise.
> Removes Hakiri, since it thinks Devise is a Rails app

- README.md
- lib/devise.rb
- lib/devise/encryptor.rb
- lib/devise/models/database_authenticatable.rb
- lib/devise/strategies/database_authenticatable.rb
- lib/generators/templates/devise.rb
- test/models/database_authenticatable_test.rb
- test/test_models.rb
Throughout the documentations, we are using 'encrypt' incorrectly.
Encrypt means that someone will eventually decrypt the message,
which is obviously not the case for Devise.
I'm changing the docs to use 'hashing' instead.
However, I left the database field as `encrypted_password` for now.
I'll update the db field in an upcoming PR.
> Change encryption for hashing in the documentation.

- CHANGELOG.md
- app/controllers/devise/confirmations_controller.rb
- app/controllers/devise/passwords_controller.rb
- app/controllers/devise/registrations_controller.rb
- app/controllers/devise/sessions_controller.rb
- app/controllers/devise/unlocks_controller.rb
- app/controllers/devise_controller.rb
- lib/devise/failure_app.rb
* Introduced `DeviseController.set_flash_message!` for conditional flash messages setting to reduce method complexity.
* Reduced complexity of `DeviseHelper#devise_error_messages!` and `Devise::FailureApp#scope_url`.
* `DeviseHelper#devise_error_messages_html` not only reduces complexity but also makes error messages easier to override by developers who want to change styling of error message.
* Changed `confirm!` to `confirm` in tests.
> Added DeviseController#set_flash_message!

- lib/devise/models/confirmable.rb
Fix confusing misuse of confirm_within variable where allow_unconfirmed_access_for should be used
> Clarify allow_unconfirmed_access_for comments in confirmation module

- app/views/devise/confirmations/new.html.erb
Though not a real issue, it was highlighted as an error by my commit
hooks, so I took the opportunity to fix it.
> Remove trailing whitespace from confirmation view

- lib/devise/omniauth/url_helpers.rb
- lib/devise/rails/routes.rb
- test/omniauth/url_helpers_test.rb
- test/routes_test.rb
This was deprecated on rails/rails#23980.
We now generate scope and provider specific routes, like `user_facebook_omniauth_callback`
or `user_github_omniauth_callback`.
We could deprecate the `omniauth_authorize_path` in favor of the generated routes, but
the `shared/links.html.erb` depends on it to generate all omniauth links at once.
Closes #3983.
> Do not use the dynamic `:action` segment on Omniauth routes.

- lib/devise/omniauth/url_helpers.rb
A deprecation layer on top of #3985 as the previous helpers no longer exists.
> Deprecate legacy OmniAuth URL helpers.

- lib/devise.rb
- lib/generators/templates/devise.rb
- test/devise_test.rb
This change add warnings for these configurations:
* `strip_whitespace_keys` - It is already explicit on config template, now
it will be the same of the template.
* `email_regexp` - In the new version this regexp will be more
permissive.
* `reconfirmable` - It is already explicit on config template, now
it will be the same of the template.
* `skip_session_storage` - It is already explicit on config template, now
it will be the same of the template.
* `sign_out_via` - It is already explicit on config template, now
it will be the same of the template.
These ones is important to change, since the configuration says current
explicit value are the default. It can lead to misunderstanging if users
remove the explicit configuration.
It also updates the template explicit values:
* Warns the …
> Add warning about default config change

- lib/devise.rb
- lib/devise/models/rememberable.rb
- lib/devise/strategies/rememberable.rb
- test/integration/rememberable_test.rb
Now the config `extend_remember_period` is used to:
`true` - Every time the user cookie is authenticated, the
cookie expiration is updated.
`false` - Does not update the cookie expiration when the cookie is authenticated.
Closes #3994
> Fix extented remember me

- lib/devise/models/database_authenticatable.rb
I'm using the [devise-nobrainer](https://github.com/nviennot/devise-nobrainer) ORM adapter with rails 5. I'm getting this error on the sign-in page: `undefined method 'attribute_will_change!'`. I assume this is because I'm not using ActiveRecord (this seems to be a method related to ActiveRecord ??). When I get rid of this line everything works as expected. So I added a conditional to make sure it exists before running it.
> Make sure attribute_will_change! method exists before calling it

- lib/devise/models/confirmable.rb
- test/models/confirmable_test.rb
Send confirmation instructions when a user updates his `email` from `nil`.
Skip reconfirmation in the case that a record is created with #save called in callbacks in a proper way.
> Send confirmation instructions when a user updates the email address from nil

- CHANGELOG.md
- lib/devise.rb
- test/integration/authenticatable_test.rb
This removes an upgrade path that migrated the old serialization format to the new one introduced. This was introduced in c22d755 (#2300) 3 years ago and should no longer be needed.
> Remove upgrade path for old session format

- lib/devise.rb
- lib/generators/templates/devise.rb
- test/devise_test.rb
- test/models/validatable_test.rb
updated `Devise::email_regexp` to meet existing test cases plus valid emails `"test@tt"` & `"test@valid---domain.com"`, non valid emails `"test_user@example..server"` & `"test_user@example-.server"`.
> updated email_regexp and added test cases

- lib/devise/failure_app.rb
- test/failure_app_test.rb
- test/integration/authenticatable_test.rb
- test/integration/confirmable_test.rb
- test/integration/database_authenticatable_test.rb
- test/integration/http_authenticatable_test.rb
If developer wants to use other authentication keys instead of email and writes in him model
```devise :database_authenticatable, authentication_keys: [:username]authentication_keys: [:user_name]```
and writes in him locale 
```
devise:
failure:
invalid: '%{authentication_keys} o contraseña no válidos.'
```
and after that user types wrong user_name or password, flash get message **"user_name  o contraseña no válidos."** instead of **"User name  o contraseña no válidos."**. Changes of this commit fix it. 
PS: sorry for my english
> Humanize authentication keys in failure flash message

- lib/devise/models/confirmable.rb
- lib/devise/models/lockable.rb
- lib/devise/models/recoverable.rb
Use friendly_token over token_generator when only raw value is needed
The first value returned by token_generator.generate is
simply the return value of friendly_token so this code should
be equivalent.
The use of token_generator here dates back to when the
confirmation_token was stored as a digest, but that is no
longer true.
> Friendly token

- lib/devise.rb
- test/devise_test.rb
- test/integration/authenticatable_test.rb
- test/integration/http_authenticatable_test.rb
- test/integration/rememberable_test.rb
- test/integration/timeoutable_test.rb
- test/integration/trackable_test.rb
- test/mapping_test.rb
- test/rails_app/config/routes.rb
- test/rails_app/lib/shared_user.rb
- test/rails_app/lib/shared_user_without_omniauth.rb
- test/routes_test.rb
In our configuration template we explicit set some configurations as recommended defaults.
Now we are enforcing these configurations to be the defaults.
It also removes all warning code about this change.
> Set the new defaults for Devise 4.1

- lib/devise/models/lockable.rb
- test/models/lockable_test.rb
A bug that if the unlock strategy was set to `:both`, it would return true for all & any inputs
See #4072
PR is an improvement on #4073
> Fix strategy checking in #unlock_strategy_enabled? for :none and undefined strategies

- Gemfile
- Gemfile.lock
- gemfiles/Gemfile.rails-4.1-stable
- gemfiles/Gemfile.rails-4.1-stable.lock
- gemfiles/Gemfile.rails-4.2-stable
- gemfiles/Gemfile.rails-4.2-stable.lock
- lib/devise/models/confirmable.rb
- test/orm/active_record.rb
Fix #4062 
Call `send_on_create_confirmation_instructions` in `after_commit` instead of `after_create`, I think this is no harm in general and it makes things like async job work.
> Send on create confirmation email after commit

- lib/devise.rb
- lib/devise/rails.rb
In #3153 we've seen that some applications require routes to be loaded before the code is eagerly loaded so we can't just remove it. However, this implies that **all** applications using Devise need to have routes reloaded twice (as was mentioned in https://github.com/plataformatec/devise/pull/3241#issuecomment-114038540). Double route reload can incur a slowdown for larger apps that have a lot of routes or a lot of controllers.
This PR strives for compromise, making the route reloading optional.
In our app, enabling this setting shaves off 15-25% of boot time in staging environment (we have more than 1500 routes).
> Make reloading of routes optional

- CHANGELOG.md
The suggested omniauth path noted in the CHANGELOG.md under 4.0.0.rc2 
did not work. It was missing an `_omniauth` in the middle of the 
method name.
user_github_authorize_path => user_github_omniauth_authorize_path
> Fix suggested omniauth path

- README.md
The Ruby code blocks have some double quotes and some single. To keep in line with [ruby best practices](https://github.com/bbatsov/ruby-style-guide#strings), I changed the double quotes to be consistent with the single quotes, which are more prevalent in the README.
> Consistency of quotation marks in README

- app/controllers/devise/registrations_controller.rb
- lib/devise/controllers/sign_in_out.rb
- test/controllers/helpers_test.rb
The sign_in method permits the bypass option
that ignore the others options used. This behavior
has lead some users to a misconfusion what the
method really does.
This change deprecate the bypass option in favor
of a method that only does the sign in with bypass.
Closes #3981
> Deprecate the bypass option of sign_in

- lib/devise/models/rememberable.rb
- test/models/rememberable_test.rb
The remember_token should not get overwritten when a user is
signing in and a valid token already exists.
Fixes #3950.
> Fix overwriting the remember_token when a valid one already exists

- CHANGELOG.md
- lib/devise/models/authenticatable.rb
- test/models/serializable_test.rb
Currently, running `inspect()` on any Devise-including model falls back to the default ActiveRecord or Mongoid behavior, which is to generate a string based on all database fields, without any sanitization. `inspect` is commonly used, including [within Devise itself](https://github.com/plataformatec/devise/blob/69bee06ceee6280b54304928bb6e55c5064abad8/lib/devise/mapping.rb#L44), as part of exception messages, and this results in the `encrypted_password` field being included in the exception. When using an external exception tracker, this can create a security disclosure issue.
This change implements `inspect`, using the existing `serializable_hash` implementation to determine which keys to include.
Before (using ActiveRecord):
#<User id: 1, username: "usertest", facebook_token: nil, …
> Implement Devise::Models::Authenticatable#inspect, re-using #serializable_hash

- lib/devise/controllers/sign_in_out.rb
When looking into performance issues in my company's rails application, I found a lot of time was spent in `Devise::Controllers::SignInOut#sign_out` whenever a user logged out. Upon closer examination, it seems the majority of the time is due to the `warden.raw_session.inspect` line. In my case, we have a very large Rails application (100s of models, 100s of controllers), so the output of that 'inspect' statement seems to take a while to process.
Tests pass despite the "Without this inspect here. The session does not clear" comment. Removing it makes sign-out seem almost instant for my use case. 
Furthermore, [this old commit](https://github.com/plataformatec/devise/commit/b786c384d54a6365bdc6c0cf6068dc5325a301a9#diff-e151dce8935252d1c6bad0356045060aL75) removes the same statement from …
> Remove unnecessary 'warden.raw_session.inspect'

- test/rails_app/config/environments/production.rb
- test/rails_app/config/environments/test.rb
I added public_file_server setting for Rails5.
Based on the warning "DEPRECATION WARNING: `config.serve_static_files` is deprecated and will be removed in Rails 5.1."
> Add public_file_server setting for Rails5

- lib/devise/failure_app.rb
- test/failure_app_test.rb
According to Ruby on Rails documentation there are 2 ways deploy your application to a subdirectory.
[doc: ](http://edgeguides.rubyonrails.org/configuring.html#deploy-to-a-subdirectory-relative-url-root)
```
class Application < Rails::Application
...
config.relative_url_root = '/my_route'
...
end
```
or
[doc: ](http://edgeguides.rubyonrails.org/configuring.html#configuring-action-controller)
```
class Application < Rails::Application
...
config.action_controller.relative_url_root = '/my_route'
...
end
```
> Add missing support of  Rails.application.config.action_controller.relative_url_root

- lib/devise/models/confirmable.rb
- test/models/confirmable_test.rb
The following commit was breaking stuff on our system for a new email confirmation when the email is changed while the object is still in memory:
https://github.com/plataformatec/devise/commit/1d57169c7bd12977a6697a5a06cda265442bb5c8
This is due to `skip_reconfirmation!` in `send_on_create_confirmation_instructions` because it sets `@bypass_confirmation_postpone` to true which lets `postpone_email_change?` return false.
The case was added to the confirmable test case. Basically, the skipping of the reconfirmation as part of an after_create hook needs to be treated differently from a general bypass. To ensure that this is skipped when save is called in an after_create hook but NOT if the email is changed from an existing email, additional checks were added.
> Change behavior to skip reconfirmation after creating a record with #save called in callback

- lib/devise/test/controller_helpers.rb
As reported here ( https://github.com/rails/rails/issues/25269 ),  ActionDispatch::IllegalStateError is raised on Rails5 RC2.
This is a workaround to solve this error.
> Test cases (not signed-in 302 redirection) failed on Rails5 RC2

- app/controllers/devise/omniauth_callbacks_controller.rb
- lib/devise/controllers/rememberable.rb
- lib/devise/failure_app.rb
- lib/devise/hooks/proxy.rb
- lib/devise/test/controller_helpers.rb
- test/rails_app/app/controllers/users/omniauth_callbacks_controller.rb
Using Rails 5.0.0.rc1 and the remember_me controller method from Devise::Controllers::Rememberable I was getting this warning a lot in my tests ```DEPRECATION WARNING: env is deprecated and will be removed from Rails 5.1```
> Fix Rails 5 env deprecation warning

- lib/devise/hooks/lockable.rb
The benefit of this commit is twofold:
1) In the Devise codebase, `update_attribute()` is only used once, while the pattern `record.attribute = value; save(validate: false)` is used in all other cases. The codebase will be more consistent.
2) This reduces the API surface an ORM must expose to support Devise. The less methods an ORM must provide to Devise, the better. For example, NoBrainer (RethinkDB ORM) does not implement such `update_attribute()` method (and probably never will due to spooky no validation feature). This would allow NoBrainer to support Devise.
Thanks :)
Nico.
> Reduce ORM API surface

- lib/generators/templates/controllers/registrations_controller.rb
- lib/generators/templates/controllers/sessions_controller.rb
Some generators produce incorrect indentations E.g.
Actual
------
```ruby
class Users::RegistrationsController < Devise::RegistrationsController
...
```
Expected
---------
```ruby
class Users::RegistrationsController < Devise::RegistrationsController
...
```
This would result in configured linters screaming about improper code. Thought i'd fix it for everyone.
> [Minor] Fix indentation in generators

- lib/devise/mailers/helpers.rb
- test/mailers/mailer_test.rb
ActionMailer's ``mail`` method may receive a block for customizing the mails
format
``devise_mail`` now has the same functionality by just passing the block to ``mail`` call.
fixes plataformatec/devise#2341
> add block passthrough to devise_mail

- test/integration/authenticatable_test.rb
Hello !
There is nothing much to this one, it's in the test's description so it shouldn't impact a thing and will make this line more greppable.
> Fix a minor typo in specs

- lib/devise/test/controller_helpers.rb
- lib/devise/test_helpers.rb
I think these deprecation warning messages should use `strip_heredoc` like others.
> Use `strip_heredoc` for deprecation warnings

- README.md
An example value of `:stretches` is `20`, which is quite slow.
For instance, take 1 minute to create an user.
When a developer set this value, it takes time to resolve the issue.
This value is set `11` [by default](https://github.com/plataformatec/devise/blob/9a11586a724487dc98dddea0ab9c8afcc0e9439d/lib/devise.rb#L71), so I think `12` is an appropriate value.
> Update README - Decrease stretches to 12

- lib/devise/models.rb
Docs say `Devise::DatabaseAuthenticatable`. 
The correct name is `Devise::Models::DatabaseAuthenticatable`.
> fix name of the module in the docs

- lib/devise/models/recoverable.rb
- test/models/recoverable_test.rb
Related to issue #4397 
This hotfix adds a string coercion to new_password paramenters when
trying to reset an user's password.
Before that, when a user submitted a password recovery form with the
new_password and new_password_confirmation params as nil, Devise would
sign in the user with a success notice but without actually changing the
password.
> Fix absent password params from Password#update

- lib/devise/models/confirmable.rb
Due to time zone difference, the confirmation link in email is invalid, this can be solved by using UTC for Time.now for confirmation_period_expired?
> Confirmation link validity is wrong in different time zone

- README.md
Update `rake db:migrate` reference to `rails db:migrate` in keeping with Rail 5 semantics.
> update rake reference to rails

- test/integration/rememberable_test.rb
- test/orm/active_record.rb
- test/rails_app/app/active_record/user.rb
- test/rails_app/app/controllers/home_controller.rb
- test/rails_app/app/controllers/users/omniauth_callbacks_controller.rb
- test/rails_app/app/controllers/users_controller.rb
- test/rails_app/config/boot.rb
- test/rails_app/lib/shared_admin.rb
- test/routes_test.rb
- test/test/controller_helpers_test.rb
~This PR does two things:~
1. I didn't like the way test specific methods are polluting the `Devise` module, so I've moved those to `Devise::Test`. This will prevent issues like #4514 from happening.
~2. Refactored the `rails51?` changes so we keep the codebase DRY.~
> Separate Devise test methods from Devise

- app/controllers/devise/omniauth_callbacks_controller.rb
Rails 5.1 has deprecated render :text, and HEAD requests on the omniauth callbacks passthru method is causing errors because the render :text is non-existant, and there's no template to fall back to.
Replacing :text with :plain, adds a content-type type of text/plain and also returns the previous message.
render :plain was supported back in rails 4.1.0
http://api.rubyonrails.org/v4.1.0/classes/ActionView/Helpers/RenderingHelper.html#method-i-render
> Rails 5.1 fix: Replaced render :text 404 with :plain in omniauth

- lib/generators/devise/views_generator.rb
Removes warning "Expected boolean default value for '--markerb'; got :erb (string)" for thor >= 0.19.2
> remove warnings about default value with new thor

- lib/generators/devise/devise_generator.rb
- test/models/validatable_test.rb
These minor changes will allow Devise to work when MRI's string literals are frozen by default. This feature of Ruby is documented here: https://wyeworks.com/blog/2015/12/1/immutable-strings-in-ruby-2-dot-3
Will over a second patch in a moment for testing this to ensure regressions are avoided.
> Ensure string literals can be frozen.

- app/controllers/devise/sessions_controller.rb
This ensures the tests are green when run on MRI 2.5.0-preview1 :)
> Fix syntax for MRI 2.5.0-preview1.

- .travis.yml
These Ruby versions are released.
https://www.ruby-lang.org/en/news/2017/09/14/ruby-2-4-2-released/
https://www.ruby-lang.org/en/news/2017/09/14/ruby-2-3-5-released/
https://www.ruby-lang.org/en/news/2017/09/14/ruby-2-2-8-released/
> CI against Ruby 2.2.8, 2.3.5, and 2.4.2

- test/orm/mongoid.rb
The problem is mongoid tests are failed due to a validation error. Like this.
```
1) Error:
DatabaseAuthenticatableTest#test_should_not_mutate_value_assigned_to_string_whitespace_key:
Mongoid::Errors::Validations: 
Problem:
Validation of User failed.
Summary:
The following errors were found: Email is already taken
Resolution:
Try persisting the document with valid data or remove the validations.
mongoid (4.0.2) lib/mongoid/persistable.rb:78:in `fail_due_to_validation!'
mongoid (4.0.2) lib/mongoid/persistable/savable.rb:45:in `save!'
/home/travis/build/plataformatec/devise/test/models/database_authenticatable_test.rb:55:in `block in <class:DatabaseAuthenticatableTest>'
```
All log I run on Travis CI is [here](https://travis-ci.org/plataformatec/devise/jobs/293096355).
When using mongoid, …
> Fix mongoid test failed problem

- Gemfile
- Gemfile.lock
I removed `gem "minitest", "< 5.10.2"` from Gemfile, because Rails 5.1.1 has already been released
> Removed gem minitest

- lib/generators/devise/views_generator.rb
It is no longer necessary to define `hide!` in `Devise::Generators::ViewPathTemplates`.
This method has already been added to `Rails:: Generators::Base` since Rails v4.0.0.beta1.
https://github.com/rails/rails/blob/master/railties/lib/rails/generators/base.rb#L55
https://github.com/rails/rails/commit/c6ef45d6c4e718b306ba8309e15ee5c1fb532878
> Remove unnecessary hide! method definition

- lib/devise.rb
- lib/devise/models/database_authenticatable.rb
Since `rails secret` can be used from Rails 5, reflects the change.
> Change `rake secret` to `rails secret` in comments

- README.md
After using `devise_scope` instead of `devise_for` I found I no longer had access to Devise helper`current_user`.
After searching I found this issue to be the answer to the problem:: https://github.com/plataformatec/devise/issues/2840
The issue is also reporter here: https://github.com/plataformatec/devise/issues/3069
I think this simple comment will clarify the issue and help other users in case they run into the same issue.
> Provide additional info on devise_scope usage

- lib/devise/controllers/helpers.rb
- test/integration/authenticatable_test.rb
This implementation replace `log_process_action` to `append_info_to_payload`  that way the status should be present in ActiveSupport::Notifications's payload and at the log
It's based on what AR is doing:
https://github.com/rails/rails/blob/92703a9ea5d8b96f30e0b706b801c9185ef14f0e/activerecord/lib/active_record/railties/controller_runtime.rb#L35
No test change was needed but one test was include.
> Replace log_process_action to append_info_to_payload

- lib/devise/models/trackable.rb
- test/models/trackable_test.rb
- test/rails_app/app/active_record/user.rb
- test/rails_app/app/active_record/user_with_validations.rb
- test/rails_app/app/mongoid/user_with_validations.rb
- test/support/helpers.rb
This commit fixes issue
https://github.com/plataformatec/devise/issues/4673
This removes `validate: false` from saving a record when `Trackable` is
in use.
Alternatively, we could use `update_attribute` to update each field individually to skip validations.
That would have the downside of making multiple database calls though.
I'd also love any other ideas on how to solve this.
> Fix missing validations on Signup

- CHANGELOG.md
- lib/devise/models/authenticatable.rb
- test/models/serializable_test.rb
The test uses `as_json` instead of `to_json` because `to_json` does `#dup` on `options` before it reaches `#serializable_hash` and the test would pass without the fix.
See also this related change in Rails: https://github.com/rails/rails/pull/27945
> Allow frozen options in as_json

- lib/devise/controllers/store_location.rb
This fairly straightforward refactor extracts the most obtuse portions of `store_location_for` into the following discrete private methods:
- `extract_path_from_location`
- `remove_domain_from_uri`
- `add_fragment_back_to_path`
This may seem like indirection but it was very unclear what operation was being performed on the location sent to store_location_for prior to this change.
I considered documenting the behavior but the code seemed like a prime candidate for method extraction.
> Clarify how store_location_for modifies URIs

- lib/devise/models/confirmable.rb
Cause of **mongoid-paperclip** declaring _after_commit_ callback while **mongoid** (and MongoDB) does not support it.
> Change the way to detect ActiveRecord vs Mongoid

- lib/generators/active_record/devise_generator.rb
- lib/generators/active_record/templates/migration.rb
- test/generators/active_record_generator_test.rb
Adds primary key type to migration creating template in Rails 5. It uses the configuration set in Rails generator as below:
```
config.generators do |g|
g.orm :active_record, primary_key_type: :uuid
end
```
Resolves #4413
> Primary key type in migration template

- app/controllers/devise/sessions_controller.rb
Our organization is still on Devise 3 but is hoping to move to Ruby 2.5. Any chance of backporting this commit?
> Backport Ruby 2.5.0 syntax fixes to 3-stable

- lib/devise/models/confirmable.rb
- test/models/confirmable_test.rb
As pointed out by @dark-panda in #4302, the condition for an `ActiveRecord` model is wrong inside the `Confirmable` initialization block.
https://github.com/plataformatec/devise/pull/4302#issuecomment-355103489
> Fix `ActiveRecord` check on `Confirmable`

- lib/devise/controllers/sign_in_out.rb
Addresses #4599
The docs previously mentioned that authentication hooks are not run when `signed_in?` is called, when in fact they are. This commit fixes the comment and suggests calling `authenticated?` on warden directly as an alternative for when you _don't_ want to run auth hooks.
> Fix `signed_in?` docs w.r.t. running auth hooks

- README.md
I've changed the section about testing in the `README.md`. I hope this makes it easier to understand how the Devise's test suite can run using multiple combinations of Ruby, Rails, and ORMs how to simulate a Travis build locally.
> Improve documentation about the test suite [ci skip]

- lib/devise/test/controller_helpers.rb
- test/test/controller_helpers_test.rb
In Rails 4, for unauthenticated controller tests which trigger the failure app, ensure that the simulated failure response includes a content_type.
This works in Rails5, which parses the content-type header on-demand, but not in Rails4 which requires setting the response's content_type explicitly.
Fixes #4783
> Fixes #4783 - preserve content_type for unauthenticated test responses

- lib/generators/templates/devise.rb
Creating a new section called `Controller configuration`.
An optional devise configuration is set `config.parent_controller`, but this configuration is missing in the `devise.rb` template file.
> Creating a new section for controller configuration on devise.rb template

- Gemfile.lock
- lib/devise/models/trackable.rb
- test/integration/authenticatable_test.rb
- test/integration/http_authenticatable_test.rb
- test/integration/omniauthable_test.rb
- test/integration/trackable_test.rb
- test/models/trackable_test.rb
- test/rails_app/app/active_record/user.rb
- test/rails_app/app/mongoid/user.rb
- test/support/integration.rb
In some cases, invalid records could be created during the signup process because we were calling `save(validate: false)` inside the `update_tracked_fields!` method. See https://github.com/plataformatec/devise/issues/4673 for more information.
This was fixed on https://github.com/plataformatec/devise/pull/4674 by calling `save` directly, but it caused some trouble and confusion since it changed Devise's behavior significantly.
We talked about on https://github.com/plataformatec/devise/issues/4790 and it doesn't even make sense to call `save` on an object that isn't persisted yet, so I've added a guard clause to the `update_tracked_fields!` method.
> Check if the record is persisted in `update_tracked_fields!`

- lib/devise/test/controller_helpers.rb
This was broken on https://github.com/plataformatec/devise/commit/3e23371b01443d6b8bdbfcbdcd33d2883847e39d#diff-bafaaa60fc003e648eb4981c9add523eR142
because of a call to the method `Devise::Test.rails5?` which is only defined in our test suite's rails app https://github.com/plataformatec/devise/blob/a45bbe1783e4b46af15825a0bb2eb5917a9b8726/test/rails_app/config/boot.rb#L19
This commits checks for the rails version directly.
Since this works inside our test suite, we haven't noticed this bug. It only happens when other projects require the controller helpers outside devise. I'm not sure how we could add an automated test for this, I accept suggestions. But I believe a better solution would be to change this class namespace for our test suite's rails app so we don't face this kind of …
> Fix `Devise::Test::ControllerHelpers`

- lib/devise/models/authenticatable.rb
- DRY up some of the sample code by refactoring into smaller methods.
- ‘Namespace’ method names to reduce chances of conflict.
- Mark `send_pending_devise_notifications`, `pending_devise_notifications`, and `render_and_send_devise_message` methods as `private` since they are only used internally.
- Update comments.
> Update sample code in Devise::Models::Authenticatable.

- guides/bug_report_templates/integration_test.rb
The integration test template was using the deprecated `before_filter` rather than `before_action`
> Use before_action instead of before_filter

- lib/devise/failure_app.rb
- lib/generators/templates/devise.rb
- test/failure_app_test.rb
- test/rails_app/config/initializers/devise.rb
- test/rails_app/lib/lazy_load_test_module.rb
Turbolinks is overwriting the redirect_to method of ActionController::Redirecting.
Devise only includes ActionController::Redirecting
So, if turbolinks is installed, it doesn't work will with devise.
This should fix it.
> Include Turbolinks if it is installed

- README.md
https://github.com/plataformatec/devise/issues/4819
In the Controller tests section of the README, it is stated that `Devise::Test::ControllerHelpers` needs to be included for devise to work in tests. 
However, from Rails 5 controller tests no longer belong to `ActionController::TestCase`, and now belong to ` ActionDispatch::IntegrationTest`. Therefore, `Devise::Test::IntegrationHelpers` needs to be included instead of `Devise::Test::ControllerHelpers`.
I added a short passage in the README explaining this difference.
> README section on controller tests should explain need for "include Devise::Test::IntegrationHelpers" in rails 5

- lib/devise/models/trackable.rb
- test/models/trackable_test.rb
This permits users to easily customize where the ip address
should be resolved.  When fronting the application with a webserver or
load balancer, the ip address may be the server and not be the user.
E.g. consider the IP address is passed as the header: "X-Forwarded-For".
```ruby
class User
devise :trackable
protected
def extract_ip_from(request)
request.headers["X-Forwarded-For"]
end
end
```
See discussion in #4540 and https://groups.google.com/forum/#!topic/plataformatec-devise/aCuFLef16Sk
Edit: updated example based on feedback changes (#get_ip => #extract_ip_from)
> Split IP resolution from update_tracked_fields

- lib/devise/controllers/sign_in_out.rb
In order to use the `sign_in` helper along with the timeoutable module, we have to set `env["devise.skip_timeout"] = true` in the request.
Currently, we do this in the sessions controller: https://github.com/plataformatec/devise/blob/master/app/controllers/devise/sessions_controller.rb#L7
This commit adds a note to the `sign_in` documentation to help other developers that want to use custom warden strategies.
Closes #4773
> Add note in the documentation about `sign_in` and timeoutable [ci skip]

- CHANGELOG.md
- app/views/devise/passwords/edit.html.erb
- app/views/devise/registrations/edit.html.erb
- app/views/devise/registrations/new.html.erb
- app/views/devise/sessions/new.html.erb
Use `autocomplete="new-password"` or `autocomplete="current-password"` to better signal browsers and password managers how to handle the password fields.
This feature is especially useful for “change your password” and “new user” forms
> Improve passwords autocomplete

- app/controllers/devise_controller.rb
Removing an additional "is" in the rdoc for DeviseController#_prefixes
> Fix in rdoc of DeviseController#_prefixes

- lib/devise/strategies/database_authenticatable.rb
- test/integration/database_authenticatable_test.rb
Addresses issue #4763.
If paranoid mode is enabled, Devise will use `devise.failure.invalid` whether or not the user is attempting to log in with an existing identifier.
Previously, log in attempts in paranoid mode were using `devise.failure.not_found_in_database` if identifier did not exist, or `devise.failure.invalid` if identifier existed but password was wrong.
> Issue 4763: Use same string on failed login regardless of whether account exists when in paranoid mode

- README.md
- guides/bug_report_templates/integration_test.rb
- lib/devise.rb
- lib/devise/failure_app.rb
- lib/devise/models/authenticatable.rb
- lib/devise/models/database_authenticatable.rb
- lib/generators/templates/devise.rb
- test/devise_test.rb
- test/failure_app_test.rb
- test/integration/confirmable_test.rb
- test/mailers/email_changed_test.rb
- test/models/confirmable_test.rb
- test/models/database_authenticatable_test.rb
- test/rails_app/config/initializers/devise.rb
- test/rails_app/lib/lazy_load_test_module.rb
Used Rails' secure_compare method inside the definition of secure_compare. This will handle the empty strings comparison and return true when both the parameters are blank strings.
Fixes #4441
> Make secure_compare handle empty strings comparison correctly

- lib/devise/parameter_sanitizer.rb
- test/parameter_sanitizer_test.rb
Hello!
When we send to devise controller string or nil instead hash in params we have error **undefined method permit' for "string":String**
This crash Rails app with 500 error and creates unnecessary records in errbit.
Example clean Rails app with Devise - https://shrouded-brook-83924.herokuapp.com
Course code -  https://github.com/b0nn1e/devise_test
**Normal case:**
`/users/sign_in?user[email]=test@example.com`
**Cases with error:** 
`/users/sign_in?user=test@example.com`
`/users/sign_in?user`
Link to reproduce bug:
-  https://shrouded-brook-83924.herokuapp.com/users/sign_in?user=string
-  https://shrouded-brook-83924.herokuapp.com/users/sign_in?user
rails 5.1.5
devise 4.4.1
ruby 2.4.2
> Fix error when params is not a hash

- lib/devise/secret_key_finder.rb
- test/secret_key_finder_test.rb
With this fix, we will try latest changes in Rails 5.2 together with standard auto-generated secret_key_base in development as a fallback.
If no specified key found, auto-generated value will be used instead.
This fixes #4864
> find auto-generated secret_key_base in development

- lib/generators/active_record/devise_generator.rb
- lib/generators/devise/orm_helpers.rb
- lib/generators/mongoid/devise_generator.rb
Hello 👋 
This refers to the discussion in #4849.
With the upcoming arrival of GDPR, I thought it would be preferable to remove the `:trackable` module from the default generator.
An IP address is considered as personal data, and storing it in the database along with tracking the user would require explicit consent from them.
I thus thought it would be a shame that a developer would get in legal trouble just because they left the `trackable` option when they first installed devise on their projects/applications (especially when using it for the first time, that's not the first thing we check or notice).
> remove :trackable from the default modules

- lib/devise/parameter_filter.rb
- test/models/database_authenticatable_test.rb
If called with a hash that has a `default` / `default_proc` configured, `Devise::ParameterFilter` can add in missing keys it was due to attempt to sanitise the values for. (This can also occur if `NilClass` has been augmented with definitions for `strip` or `downcase`.)
A side effect of this is that reset tokens were preventing from being used; the workaround in place was to set `config.authentication_keys = config.strip_whitespace_keys = []`, as described in issue #3431.
This patch prevents this from happening, whilst also clarifying the filtering intent of `ParamaterFilter`.
_Current behaviour, before patch:_
```ruby
conditions = { 'present' => 'present_val' }
conditions.default = ''
Devise::ParameterFilter.new(['not_present'], []).filter(conditions)
```
_New behaviour, with patch:_ …
> Fix bug: `ParameterFilter` should not add keys (#3431)

- README.md
since the ssl certificate is only valid for www.rubydoc.info (not rubydoc.info)
> update rubydoc.info links in README to the url `www.rubydoc.info`

- app/controllers/devise/registrations_controller.rb
Added  is_navigational_format? check to after_sign_up_path_for,  as the issue #4356 requested.  Tests are passing.
> issue 4356 adds is_navigational_format? check to after_sign_up_path_for

- lib/generators/templates/simple_form_for/registrations/edit.html.erb
#4931 
Just a very small syntax error (missing comma in the argument list)
> Missing comma in form input

- lib/devise/models/database_authenticatable.rb
- test/models/database_authenticatable_test.rb
I added methods to skip email change notifications and password change notifications on per edit basis like the issue was requesting.  I also added tests for these two methods.  All the tests are passing and the functionality worked when I tried it out on my test app.  This is my first PR so please let me know if I missed conforming to any guidelines or if I need to improve or adjust the code to fit your structure better. Thanks!
> issue 4526 adds skip email and password change notifications methods

- lib/devise/controllers/helpers.rb
- lib/devise/failure_app.rb
- test/controllers/helpers_test.rb
- test/failure_app_test.rb
In cases, such as a rails api controller `ActionController::API`, the request object does _not_ have flash capabilities loaded.  The `is_flashing_format?` should gracefully return false in those cases.
Addresses #4947
> Fix to calling flash when the request object doesn't support it

- lib/devise/models/database_authenticatable.rb
- test/models/database_authenticatable_test.rb
After merging #4261, I realized that we could add a couple more tests, to ensure the new behavior added to `#valid_password?` - which is that it should return `false` when the password is either `nil` or blank (`""`).
I've also removed [this condition](https://github.com/plataformatec/devise/blob/master/lib/devise/models/database_authenticatable.rb#L68) because it's already present at `Devise::Encryptor` module in the `.compare` [method](https://github.com/plataformatec/devise/blob/master/lib/devise/encryptor.rb#L15).
> Add more tests

- lib/generators/devise/controllers_generator.rb
Hello. I found one little mistake in controllers generator's description. When I run command ```rails generate devise:controllers```  I see
```
For example:
rails generate devise:controllers users -c=sessions
This will create a controller class at app/controllers/users/sessions_controller.rb like this:
class Users::ConfirmationsController < Devise::ConfirmationsController
content...
end
```
You show how to overwrite sessions controller, but use the code of ConfirmationsController 😅
> fixed description for Devise::Generators::ControllersGenerator

- lib/devise/models/authenticatable.rb
- test/models/authenticatable_test.rb
The `Authenticatable::find_or_initialize_with_errors` class method loads a record based on given attributes, or instantiates a new one if it does not exist. It depends on `ParameterFilter` to filter/sanitize the input attributes as appropriate (_e.g.,_ downcasing case-insensitive keys or stripping whitespace).
In its current form, it only does this parameter filtering when loading an existing record (by way of `::find_first_by_auth_conditions`) — that is, it does not filter input attributes when instantiating a new resource.
This PR ensures that parameters are filtered for new records as well. I also took the liberty of doing some refactoring.
> [bugfix] [refactoring] Sanitize parameters in find_or_initialize_with_errors

- devise.gemspec
RubyGem only needs the`lib, app, config`, special it for avoid the useless file packing into the gem file.
> Ignore useless files into the gem file.

- Gemfile
- Gemfile.lock
- gemfiles/Gemfile.rails-4.1-stable
- gemfiles/Gemfile.rails-4.1-stable.lock
- gemfiles/Gemfile.rails-4.2-stable
- gemfiles/Gemfile.rails-4.2-stable.lock
- gemfiles/Gemfile.rails-5.0-stable
- gemfiles/Gemfile.rails-5.0-stable.lock
- gemfiles/Gemfile.rails-5.2-rc1
- gemfiles/Gemfile.rails-5.2-rc1.lock
- lib/devise/models/confirmable.rb
- test/models/confirmable_test.rb
- test/test_helper.rb
If `Confirmable#confirmation_sent_at` is equal to `0.days.ago`, then `confirmation_period_valid?` will be deemed valid even if the setting is configured to disable this outright. To prevent this
error, we explicitly check the configuration setting to be `0.days.ago`.
> Fix corner case when confirmation_sent_at is equal to 0.days.ago

- app/helpers/devise_helper.rb
- app/views/devise/confirmations/new.html.erb
- app/views/devise/passwords/edit.html.erb
- app/views/devise/passwords/new.html.erb
- app/views/devise/registrations/edit.html.erb
- app/views/devise/registrations/new.html.erb
- app/views/devise/shared/_error_messages.html.erb
- app/views/devise/unlocks/new.html.erb
This should make it more intuitive and easier for developers using the project to implement their own layout for errors.
> Refactor the devise_error_messages! helper to render a partial

- app/helpers/devise_helper.rb
- app/views/devise/shared/_error_messages.html.erb
- Add a deprecation warn for `DeviseHelper.devise_error_messages!`
- Fix unclosed `li` tag in `error_messages` partial
> Fix unclosed html tag and add deprecation warn

- app/controllers/devise/sessions_controller.rb
- test/controllers/sessions_controller_test.rb
This PR is for issue #4782  @tegon
To clarify the 3 tests added:
- This was the original behavior before I made any changes. I simply added this test to ensure this was not broken after my implementation.  
- This is the new behavior added.
- This was the original behavior before I made any changes. I simply added this test to ensure this was not broken after my implementation.
> Modified sessions controller to return 401 for destroy action with no user signed in

- lib/devise/models/lockable.rb
- test/models/lockable_test.rb
As reported in #4981, the method `#increment_failed_attempts` of `Devise::Models::Lockable` was
not concurrency safe. The increment operation was being done in two steps: first the value was read from the database, and then incremented by 1. This may result in wrong values if two requests try to update the value concurrently. For example:
```
Browser1 -------> Read `failed_attempts` from DB (1) -------> Increment `failed_attempts` to 2
Browser2 -------> Read `failed_attempts` from DB (1) -------> Increment `failed_attempts` to 2
```
In the example above, `failed_attempts` should have been set to 3, but it will be set to 2. 
This pull request handles this case by calling `ActiveRecord::CounterCache.increment_counter` method, which will do both steps at once, reading the value straight from …
>  Make `#increment_failed_attempts` concurrency safe

- lib/devise/failure_app.rb
- test/failure_app_test.rb
- test/integration/authenticatable_test.rb
- test/integration/confirmable_test.rb
- test/integration/database_authenticatable_test.rb
- test/integration/http_authenticatable_test.rb
> Downcase authentication keys and humanize error message

- CHANGELOG.md
The current link to the README file in the CHANGELOG.md file is broken.
> Fixed broken README link in CHANGELOG.md

- lib/devise/test/controller_helpers.rb
This fixes an issue that raises an `ActionDispatch::IllegalStateError` in tests
```
1) Users::SessionsController request/response duration #create bad password behaves like ideal duration is close to ideal standardised duration
Failure/Error: post :create, params: { user: { email: email, password: password } }
ActionDispatch::IllegalStateError:
header already sent
Shared Example Group: "ideal duration" called from ./spec/controllers/users/sessions_controller_spec.rb:36
#[redacted]/gems/rails-controller-testing-1.0.4/lib/rails/controller/testing/integration.rb:13:in `block (2 levels) in <module:Integration>'
```
> Apply Test Helper fix to Rails 6.0 as well as 5.x

- lib/devise/failure_app.rb
- test/integration/mounted_engine_test.rb
I've been able to fix the issue for https://github.com/plataformatec/devise/issues/4127#issuecomment-309112353 though I'd like some help to create the test. 
It's pretty simple: the engine should point to a directory inside the engine, in order to trigger the redirect. Then the test would be:
```ruby
test 'redirect to login page when browsing an internal route without being authenticated' do
get '/mountable_engine/some_route'
follow_redirect!
assert_response :success
assert_contain 'Rendered content of MyMountableEngine'
end
```
@basiszwo, how can I add to [your code](https://github.com/plataformatec/devise/blob/cbbe932ee22947fb7fc741a4da3e6783091c88b0/test/integration/mounted_engine_test.rb#L3-L7) an internal route `some_route ` in order to test it?
> FIX plataformatec/devise#4127

- README.md
- bin/test
The command bin/test stop running single tests once Devise started to support Rails 5.2. The problem is because we used `rails/test_unit/minitest_plugin` and this file was moved to another place.
See: https://github.com/rails/rails/pull/29572
I'm not sure if we should require the `minitest-plugin` directly from Rails like we were doing, I tried it and it didn't work. So I'm changing this `bin/test` completely based on how Rails does that [here](https://github.com/rails/rails/blob/master/tools/test.rb)
> Fix bin/test using Rails::TestUnit

- test/support/webrat/integrations/rails.rb
Forwarding methods to private methods is deprecated and produces a warning after Ruby 2.4.
see: https://bugs.ruby-lang.org/issues/12782
To fix this issue I'm mocking patching webrat making RailsAdatper#response method public since Webrat::Session is delegating functions to it.
> Fix webrat warnings

- lib/devise/failure_app.rb
- test/failure_app_test.rb
When an application does not define a [`root`](https://api.rubyonrails.org/classes/ActionDispatch/Routing/Mapper/Resources.html#method-i-root), the method will be undefined instead of returning a falsey value. This used to work before version 4.6.0, but after 1aab449 it throws an error.
This pull request also includes a new test with fake objects that mimic this behavior.
Fixes #5021.
> Check if `root_path` is defined with `#respond_to?` instead of `#present`

- app/controllers/devise/passwords_controller.rb
- config/locales/en.yml
- test/controllers/passwords_controller_test.rb
- test/integration/recoverable_test.rb
Addresses issue #4399.
The flow of `PasswordController#update` re-rendered the edit view whenever there was an error resetting the password. But if the error was that the token has expired the message said "Reset password token has expired, please request a new one" — with no instructions on how to do that. 
This pull requests changes the behavior such that if the error is an expired password token, devise redirects to the `new_password_path`. That way the user has the form in front of them to make that request.
> When password reset token expires, redirect to new password path

- lib/devise/models/lockable.rb
- test/models/lockable_test.rb
> Backport CVE-2019-5421 fix to 3.x

- lib/devise/models/database_authenticatable.rb
- test/models/database_authenticatable_test.rb
Closes #5033 
More info in https://github.com/plataformatec/devise/issues/5033#issuecomment-476386275.
> Reverts both "[#4245] Allow password to nil (#4261)" and "Add more tests (#4970)"

- CHANGELOG.md
- app/views/devise/passwords/edit.html.erb
- lib/generators/templates/simple_form_for/passwords/edit.html.erb
Update `password_confirmation` fields to include the correct `autocomplete` parameter, based on the discussions [here](https://github.com/plataformatec/devise/pull/4851#discussion_r271034695) and [here](https://github.com/plataformatec/devise/commit/6260c29a867b9a656f1e1557abe347a523178fab#r31284249).
> Update password confirmation autocomplete

- lib/devise/failure_app.rb
fix https://github.com/plataformatec/devise/commit/1aab4499330c8a7641a3dea7e2ec3b96acdf46ae
> refactor method name to be more consistent

- lib/devise/models/validatable.rb
Rails 6 rc1 introduced a deprecation in uniqueness-validation:
> Uniqueness validator will no longer enforce case sensitive comparison in Rails 6.1. To continue case sensitive comparison on the case insensitive column, pass case_sensitive: true option explicitly to the uniqueness validator.
this PR fixes produced error.
Fixes #5064
> Fix rails 6.0.rc1 email uniqueness validation deprecation error

- README.md
The previous link gave 404 error.
Update with newer working link.
> Updated Codeacademy's Rails Auth link

- lib/devise/rails/routes.rb
Comment incorrectly states that default method used while signing out is `:get`, while [line 228 of /lib/devise.rb](https://github.com/plataformatec/devise/blob/master/lib/devise.rb#L228) sets `:delete`: 
> \# The default method used while signing out: 
> mattr_accessor :sign_out_via
> @@sign_out_via = :delete
> Update Options section of comment in routes.rb 

- test/orm/active_record.rb
- test/rails_app/app/views/admins/sessions/new.html.erb
- test/rails_app/config/application.rb
- test/rails_app/config/boot.rb
- test/test/controller_helpers_test.rb
The `ActiveRecord::MigrationContext` class now has a `schema_migration` attribute.
Reference: https://github.com/rails/rails/pull/36439/files#diff-8d3c44120f7b67ff79e2fbe6a40d0ad6R1018
This pull request also includes some changes to avoid deprecation warnings: https://github.com/plataformatec/devise/commit/3273f9e08943deb1b413268392bb640512aee799, https://github.com/plataformatec/devise/commit/77cb3941ec3c198435309370c9e538ab1339a378 and https://github.com/plataformatec/devise/commit/69534c666c66a30c4e1c814c0c15846059f35dcc
> Fix specs on Rails 6 RC2

- lib/devise/models/confirmable.rb
- test/integration/confirmable_test.rb
- test/models/confirmable_test.rb
As reported in #5071, if for some reason, a user in the database had the `confirmation_token`
column as a blank string, Devise would confirm that user after receiving a request with a blank `confirmation_token` parameter.
After this commit, a request sending a blank `confirmation_token` parameter will always receive a validation error, even if there are users with a blank `confirmation_token` in the database.
For applications that have users with a blank `confirmation_token` in the database, it's recommended to manually regenerate or to nullify them.
Closes #5071
> Always return an error when `confirmation_token` is blank

- CHANGELOG.md
- README.md
- lib/devise.rb
- lib/generators/templates/devise.rb
Test script
---
```ruby
require 'bcrypt'
require 'benchmark'
Benchmark.measure { BCrypt::Password.create('password', cost: 12) }
```
Test results
---
- [Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz](https://ark.intel.com/content/www/us/en/ark/products/97535/intel-core-i5-7360u-processor-4m-cache-up-to-3-60-ghz.html): `#<Benchmark::Tms:0x00007fdd00a4eb30 @label="", @real=0.21730700000080105, @cstime=0.0, @cutime=0.0, @stime=0.00020399999999999585, @utime=0.21685199999999996, @total=0.21705599999999997>`
- [Intel(R) Core(TM) i7-8559U CPU @ 2.70GHz](https://ark.intel.com/content/www/us/en/ark/products/137979/intel-core-i7-8559u-processor-8m-cache-up-to-4-50-ghz.html): `#<Benchmark::Tms:0x00007fe91094fd30 @label="", @real=0.17964200000278652, @cstime=0.0, @cutime=0.0, …
> Increase default stretches to 12

- lib/generators/devise/views_generator.rb
- test/generators/views_generator_test.rb
Added tests for `error_messages` file and content to be present in generated views, and the generated views to use scoped errors in place of default devise errors.
Fixes #5066
> Using scoped errors for scoped views. Fixes #5066

- lib/devise/controllers/helpers.rb
- lib/devise/controllers/sign_in_out.rb
- test/controllers/helpers_test.rb
Previously checks whether a certain scope is signed in were performed using warden’s
`authenticate?` or `authenticate` methods which would run the strategies and sign in the
scope if valid params were given. We want to remove this side effect from query methods.
Fixes #5013
> Use warden’s `authenticated?` for query methods to avoid side effects

- app/controllers/devise_controller.rb
- test/integration/authenticatable_test.rb
The flash accessor is being called directly instead of the #set_flash_message helper. The PR change this behavior calling `set_flash_message` helper.
fixes #5080
> Call set_flash_message helper instead of flash accessor

- lib/devise/models/authenticatable.rb
When using the example async code, the first notification sent (:email_changed), it says "your email is being changed to <existing_email>", which is a bug.
This is due to https://github.com/rails/rails/commit/16ae3db5a5c6a08383b974ae6c96faac5b4a3c81 `changed?` has been updated to check for dirtiness after save. Because it checks for dirtiness after save, it does not wait until after_commit before sending the notification.
The new method that behaves like the old `changed` is `saved_changes?`.
> `changed?` behaviour has been updated

- test/integration/trackable_test.rb
This PR changed the below.
- Add assert case to integration test of Lockable
- Replace mathcer **assert_not** to **refute** in model test of Trackable
I added a below test case to `test/integration/trackable_test.rb#47`.
Add line for check last_sign_in_ip value.
```ruby
assert_equal arbitrary_ip, user.last_sign_in_ip
```
This is because `assert_equal arbitrary_ip, user.current_sign_in_ip` 's test is exist but the above case I added was not in this test file. 
Replace mathcer **assert_not** to **refute**.
**assert_not** matcher is only used in `test/models/trackable_test.rb#49-50` and `test/models/trackable_test.rb#60` . However other testcases use **refute** so I replaced it.
> Add assert to Lockable integration test and Replace mathcer `assert_not` to `refute`

- README.md
- lib/generators/templates/README
- lib/generators/templates/devise.rb
This is a bit of a knock on PR related to #4947 specifically addressing documentation.
I have been experimenting more and more with rails api-only application leveraging devise this PR attempts to make a solid attempt to stem the documentation issues (or really lack thereof) from creating unnecessary noise as bugs or feature requests.
> Documentation: Details/Notes regarding Rails API-only applications

- app/controllers/devise_controller.rb
- lib/devise/failure_app.rb
This prevents us from using behavior that was deprecated in Ruby 2.7.
I was getting these lines in my test suite with Ruby 2.7, this change fixes them:
```
/Users/connorshea/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/devise-4.7.1/lib/devise/failure_app.rb:110: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/Users/connorshea/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/i18n-1.7.0/lib/i18n.rb:179: warning: The called method `t' is defined here
/Users/connorshea/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/devise-4.7.1/app/controllers/devise_controller.rb:187: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/Users/connorshea/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/g …
```
> Fix two deprecated usages of keyword arguments.

- README.md
Paragraph defaults to description of how to test in Rails 5/6 now.
> update README to reflect current Rails version

- lib/devise/hooks/timeoutable.rb
move timeout_skip check earlier to avoid unnecessary record lookup
> Performance improvement for timeoutable

- lib/devise/models/database_authenticatable.rb
`DatabaseAuthenticable` overrides the `password=` method in a model, bypassing setting that attribute, and this should be reflected in the documentation.
We got bitten by this at work because we're using a legacy database where the User model already has a `password` field and upon the introduction of Devise the password stopped being stored there; we had to override the method again to get our needed behaviour but having this in the documentation would've saved us a few hours of debugging.
Thanks!
> Clarify DatabaseAuthenticable's behaviour for password fields

- lib/generators/devise/devise_generator.rb
Hi,
I use the `devise` and [`devise-specs`](https://github.com/andrii/devise-specs) gems.
And I checked with `byebug` to discover where was located this bug.
In https://github.com/andrii/devise-specs/blob/master/lib/devise/specs/railtie.rb, the problem goes with this line:
```ruby
require 'generators/devise/devise_generator'
```
So the `devise_generator.rb` file is being called https://github.com/heartcombo/devise/blob/master/lib/generators/devise/devise_generator.rb
And this error is finally being raised:
```bash
rails generate devise:specs User
Deprecation warning: Expected string default value for '--orm'; got false (boolean).
This will be rejected in the future unless you explicitly pass the options `check_default_type: false` or call `allow_incompatible_default_type!` in your code …
```
> Fix Deprecation warning: Expected string default value for '--orm'

- lib/generators/devise/install_generator.rb
`rails_4?` is not called anymore since 2024fca4dfa3323070c3477e262b8422cadf6a42.
> Remove unused method from Devise::Generators::InstallGenerator

- README.md
Warden moved to its own organization so we should follow it.
> Correct warden URL in README [ci skip]

- lib/devise.rb
`self.rails51?` method is not using in `lib`, and the Only `test` uses the method.
I guess better to remove this method.
> remove useless rails51? method

- README.md
- Remove the anchor link to Heroku under Additional information (it was taking you nowhere)
- Consistent spelling for behavior (there were two versions: behaviour and behavior)
- Consistent spelling for Mongoid 
- Typo: Leaonardo Tegon -> Leonardo Tegon
Thanks!
> Remove Heroku anchor link and fix some typos

- lib/generators/devise/devise_generator.rb
The `:orm` option can also have symbol values.
Fixes https://github.com/heartcombo/devise/issues/5252.
> Fix warning from `thor`

- lib/devise/controllers/sign_in_out.rb
Seven years ago rails `session.keys` could be empty if the session was not loaded yet.
To prevent an error the removed code was introduced
https://github.com/heartcombo/devise/issues/2660
Since then rails changed the behavior and makes sure that the session is loaded before someone wants to access any session keys
https://github.com/rails/rails/blob/3c99817394f634710a6280c5d5512c0ea663bce3/actionpack/lib/action_dispatch/request/session.rb#L120
Which means the `session.empty?` is not needed anymore
> chore: Cleanup old rack/rails session bug fix

- config/locales/en.yml
- test/integration/registerable_test.rb
Added missing full stop "." on registrations.updated_but_not_signed_in.
> Add missing period to devise.registrations.updated_but_not_signed_in

- README.md
This changed in https://github.com/rails/rails/commit/229fd2a02fc694b4b7756445b6647777aa94e25d - the advice about changing your log level still stands though.
> Fix Rails default log level

- Gemfile
- Gemfile.lock
- app/views/devise/shared/_links.html.erb
- test/integration/omniauthable_test.rb
Hope this helps with https://github.com/heartcombo/devise/pull/5327. Updated omniauthable links to use `method: :post` and revised corresponding tests.  I opened a PR with omniauth-openid (https://github.com/omniauth/omniauth-openid/pull/44), but for now I updated the Gemfile to pull it from a branch on my fork.
> Update omniauthable tests for OmniAuth 2.0

- README.md
changed 'support' to 'supports'
> typo in documentation

- lib/generators/active_record/devise_generator.rb
The warning was added in https://github.com/rails/rails/pull/38256
> Fix deprecation warning on Rails 6.1

- devise.gemspec
Add the various links to RubyGems so people can go directly to various places such as the changelog when upgrading.
> Add metadata for RubyGems

- README.md
- devise.gemspec
- lib/devise/controllers/sign_in_out.rb
Hi, I use devise gem helpful.
I created a pull request to replace urls in the repository that contain `master` with `main`.
While reading the README.md, I found 404 not found link.
This is due to the fact that the urls in in this repository are written with `master` branch but there is not actually exist.
(It seems that the `main` branch recently moved from `master` branch.)
> Update the urls which refer nonexistent master branch name in documentations

- CHANGELOG.md
- lib/devise/models/validatable.rb
- test/models/validatable_test.rb
Expand tests to check for the actual validatable exception message
This was raising a `FrozenError` on Ruby < 3 where interpolated strings
were considered frozen. This [changed in Ruby 3], since such strings are
dynamic there's no point in freezing them by default.
The test wasn't catching this because `FrozenError` actually inherits
from `RuntimeError`:
>> FrozenError.ancestors
=> [FrozenError, RuntimeError, StandardError, Exception, Object ...]
So the exception check passed. Now we're also checking for the error
message to ensure it raised the exception we really expected there.
Closes https://github.com/heartcombo/devise/pull/5465
> Fix frozen string in validatable module

- CHANGELOG.md
- lib/devise.rb
- lib/devise/models.rb
- lib/devise/models/confirmable.rb
- lib/devise/models/database_authenticatable.rb
- lib/devise/models/recoverable.rb
- lib/devise/models/validatable.rb
- lib/devise/orm_dirty_tracking.rb
- test/rails_app/lib/shared_admin.rb
We have an number of conditions due to how dirty tracking changed around Rails 5.1, that implement methods using one or another method call. I might need more of this for mongo upgrades based on an initial investigation, plus this makes the code really hard to reason about sometimes with these many conditionals.
While I want to drop support for older versions of Rails soon, this centralization of dirty methods that are used by devise conditionally simplifies the usage considerably across the board, moves the version condition to a single place, and will make it easier to refactor later once we drop older Rails version by simply removing the `devise_*` versions of the methods, alongside the prefix on the method calls for the most part, since those methods follow the naming of the newer …
> Refactor dirty tracking conditionals for different versions

- CHANGELOG.md
- lib/devise/failure_app.rb
- test/failure_app_test.rb
It appears some people use the recall functionality with a redirect
response, and Devise starting on version 4.9 was overriding that status
code to the configured `error_status` for better Turbo support, which
broke the redirect functionality / expectation.
While I don't think it's really great usage of the recall functionality,
or at least it was unexpected usage, it's been working like that
basically forever where recalling would use the status code of the
recalled action, so this at least keeps it more consistent with that
behavior by respecting redirects and keeping that response as a redirect
based on the configured status, which should also work with Turbo I
believe, and makes this less of a breaking change.
Closes https://github.com/heartcombo/devise/issues/5570
Closes …
> Respect redirect status code when recalling the action

- CHANGELOG.md
- lib/devise.rb
- lib/devise/models.rb
- lib/devise/models/confirmable.rb
- lib/devise/orm.rb
Devise is able to work with a specific ORM, either Active Record or Mongoid, but nothing stops apps from using multiple ORMs within the same application -- they just need to pick one to use with Devise. That's generally determined by the require that is added to the Devise initializer, that will load up either ORM's extensions so you can call things like `devise` on your model to set it up.
However, some conditional logic in Devise, more specifically around dirty tracking, was only considering having Active Record loaded up after a certain version, to determine which methods to call in parts of the implementation. In a previous change we refactored all that dirty tracking code into this `OrmDirtyTracking` module to make it easier to view all the methods that were being conditionally …
> Improve support for Devise in apps with multiple ORMs loaded

- app/helpers/devise_helper.rb
- lib/devise.rb
- lib/devise/controllers/sign_in_out.rb
- lib/devise/models/authenticatable.rb
- lib/devise/models/database_authenticatable.rb
- lib/devise/rails.rb
- lib/devise/test/controller_helpers.rb
- lib/devise/test_helpers.rb
- test/devise_test.rb
- test/models/serializable_test.rb
- test/rails_test.rb
- test/test_helper.rb
Rails 7.1 will deprecate using the singleton ActiveSupport::Deprecation instance (https://github.com/rails/rails/pull/47354). This defines one for the gem and uses it.
> Use a dedicated ActiveSupport::Deprecation

- test/orm/active_record.rb
- test/rails_app/config/environments/test.rb
While running the tests for #5583 against Rails main I noticed these deprecations.
> Fix Rails main deprecations

- app/views/devise/confirmations/new.html.erb
- app/views/devise/passwords/edit.html.erb
- app/views/devise/passwords/new.html.erb
- app/views/devise/registrations/edit.html.erb
- app/views/devise/registrations/new.html.erb
- app/views/devise/sessions/new.html.erb
- app/views/devise/shared/_links.html.erb
- app/views/devise/unlocks/new.html.erb
In regular HTML `<br>` is a void element, so it doesn't
need a closing tag or a closing slash. See the WhatWG
spec here: https://html.spec.whatwg.org/multipage/text-level-semantics.html#the-br-element
Many of the shared templates used by devise use `<br/>`
to separate lines. To make that more correct I've replaced
them with `<br>` instead.
> Replaced `<br/>` with `<br>`

- CHANGELOG.md
- lib/devise/models/authenticatable.rb
- test/models/serializable_test.rb
This deprecation warning worked for us, but it has served its purpose.
It was added over 2 years ago now, isn't that long enough to trigger a deprecation warning?
https://github.com/heartcombo/devise/blob/main/CHANGELOG.md#480---2021-04-29
Now that I've given it enough time, I've removed this as I think it's noise for many people who don't see `Devise::Models::Authenticatable::BLACKLIST_FOR_SERIALIZATION`.
However, `Devise::DeprecatedConstantAccessor`, which was added in the same commit, is not referenced anywhere else, but has not been removed as it may be used in the future. Please let me know so I can delete it if necessary.
These source codes were added in the PR below:
https://github.com/heartcombo/devise/commit/0c2cab7c946e0796c673a36aebba7c0352e5fec8
> Removed deprecations warning output for `Devise::Models::Authenticatable::BLACKLIST_FOR_SERIALIZATION`

- lib/devise/mailers/helpers.rb
- test/mailers/mailer_test.rb
Rails allow `procs` and `lambda` with either zero or more argument as values for the different defaults. Devise however always tried to call `instance_eval` on those values, which does always pass one argument: `self`.
There was a PR to fix this specific problem in Devise https://github.com/heartcombo/devise/pull/4627, before the arity check was fixed in rails itself: https://github.com/rails/rails/pull/30391.
But even if the problem was fixed in Rails, Devise was still calling the proc/lambas with `instance_eval`. That meant the fix added to Rails did not apply to Devise.
The fix is to let Rails handle the `:from` and `:reply_to` defaults. We do that by unsetting the corresponding headers instead of duplicate the way Rails handles callables in Devise. This lets Rails handle the values …
> Make sure Mailer defaults :from and :reply_to are handled correctly

- lib/devise/rails/routes.rb
- test/integration/omniauthable_test.rb
Use Omniauth.allowed_methods' as routing verbs for the auth path:
- ### Context
Since version 2.0.0, Omniauth no longer recognizes `GET` request
on the auth path (`/users/auth/<provider>`). `POST` is the only
verb that is by default recognized in order to mitigate CSRF
attack. https://github.com/omniauth/omniauth/blob/66110da85e3106d9c9b138d384267a9397c75fe7/lib/omniauth/strategy.rb#L205
Ultimatelly, when a user try to access `GET /users/auth/facebook`,
Devise [passthru action](https://github.com/heartcombo/devise/blob/6d32d2447cc0f3739d9732246b5a5bde98d9e032/app/controllers/devise/omniauth_callbacks_controller.rb#L6) will be called which just return a raw 404 page.
There is no problem per se and everything work. However the
advantage of not matching GET request at the router layer allows …
> Use Omniauth.allowed_methods' as routing verbs for the auth path:

- README.md
Removes the dollar sign from the beginning of terminal commands.
When the commands that have the terminal beginning of line symbol in front of them are copied to the clipboard using the copy button in the code block, the user has to first remove the symbol to run the command. Running the command without first removing this symbol will result in an error.
Remove the terminal beginning of line symbol so that the user can click the button in the code block to copy to clipboard and then simply past the command in the terminal and press the return key to run it.
N/A
N/A
No.
> Make copying and pasting terminal commands easier

- CHANGELOG.md
- lib/devise/rails/deprecated_constant_accessor.rb
This is a follow-up to the PR below:
- https://github.com/heartcombo/devise/pull/5583
- https://github.com/heartcombo/devise/pull/5598
`rails` has deprecated the use of `ActiveSupport::Deprecation` in singleton in [this PR](https://github.com/rails/rails/pull/47354/files), so `devise` has defined its own `Deprecator` in response to this, but there was an omission in the correction. So I fixed it.
Please note that a PR has been created that will discontinue support for EOL rails versions, and the files modified this time may also be deleted.
https://github.com/heartcombo/devise/pull/5600
> Fixed missing migration to dedicated deprecator

- README.md
- lib/generators/templates/devise.rb
I noticed this very minor typo while setting up a project and thought I might as well fix it.
> Fix typo in config template

- CHANGELOG.md
- app/controllers/devise/sessions_controller.rb
- lib/devise/controllers/helpers.rb
- lib/devise/failure_app.rb
- test/controllers/helpers_test.rb
- test/failure_app_test.rb
- test/integration/authenticatable_test.rb
- test/rails_app/app/controllers/admins_controller.rb
- test/support/locale/pt-BR.yml
- test/test_helper.rb
A common usage of I18n with different locales is to create some around callback in the application controller that sets the locale for the entire action, via params/url/user/etc., which ensure the locale is respected for the duration of that action, and resets at the end.
Devise was not respecting the locale when the authenticate failed and triggered the failure app, because that happens in a warden middleware right up in the change, by that time the controller around callback had already reset the locale back to its default, and the failure app would just translate flash messages using the default locale.
Now we are passing the current locale down to the failure app via warden options, and wrapping it with an around callback, which makes the failure app respect the set I18n locale by the …
> Respect locale set by controller in the failure app

- README.md
Very small one - the heading for 'Active Job Integration' doesn't match the link in the TOC. This fixes that link.
> Fix README anchor link

- .github/workflows/test.yml
This PR adds Ruby 3.3 in the CI matrix.
It excludes rubies that are incompatible with Rails 7.2
```
Because every version of rails depends on Ruby >= 3.1.0
and Gemfile-rails-main depends on rails >= 0,
Ruby >= 3.1.0 is required.
```
> Adds Ruby 3.3 to CI

- gemfiles/Gemfile-rails-main
Fixes the following CI failures that were triggered by https://github.com/heartcombo/devise/pull/5706:
- https://github.com/heartcombo/devise/actions/runs/10418314232/job/28889211134?pr=5706
- https://github.com/heartcombo/devise/actions/runs/10418314232/job/28889211187?pr=5706
- https://github.com/heartcombo/devise/actions/runs/10418314232/job/28889211219?pr=5706
The errors happen because Rails 8 now requires sqlite gem >= 2.0 after this commit was merged: https://github.com/rails/rails/pull/51958.
> Rails 8: Fix CI sqlite3 error for Gemfile-rails-main

- lib/devise/rails/routes.rb
Running devise against the main branch of rails I get the following error:
```
ArgumentError:
'{:only=>[:new, :create, :edit, :update, :destroy], :path=>"", :path_names=>{:new=>"sign_up", :edit=>"edit", :cancel=>"cancel"}, :controller=>"devise/registrations"}s' is not a supported controller name. This can lead to potential routing problems. See [https://guides.rubyonrails.org/routing.html#specifying-a-controller-to-use](https://guides.rubyonrails.org/routing.html#specifying-a-controller-to-use)
No examples found.
```
It looks like it's been caused by this PR getting merged: https://github.com/rails/rails/pull/52605
After updating this call to use keyword arguments, the error doesn't happen any more
> Rails 8: Update route registration to use keyword arguments

- lib/devise.rb
See:
* https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/checkbox#attr-value
* https://html.spec.whatwg.org/multipage/input.html#checkbox-state-(type%3Dcheckbox)
* https://html.spec.whatwg.org/multipage/input.html#dom-input-value-default-on
This issue causes the remember me functionality not to work correctly, especially when overriding the default styles as check boxes by default in all major browsers send the value `on` as required by the HTML specifications.
See also:
https://stackoverflow.com/questions/5987075/devise-remember-me-not-working-localhost-issue
> Bug Fix: Devise Checkbox TRUE VALUES not compatible with HTML specs (missing "on" value)

- CHANGELOG.md
- lib/devise.rb
Starting from Rails 8.0, routes are lazy-loaded by default in test and development environments. However, Devise's mappings are built during the routes loading phase. To ensure it works correctly, we need to load the routes first before accessing `@@mappings`.
Closes https://github.com/heartcombo/devise/issues/5705 https://github.com/heartcombo/devise/pull/5695
> Make Devise.mappings work with lazy loaded routes.

- .github/workflows/test.yml
CI is currently failing for Gemfile-rails-main because Rails 8+ requires Ruby 3.2+.
This PR tweaks the CI config to ignore Rails 3.1 for Rails main.
> Fix Rails main CI

- CHANGELOG.md
- lib/devise/rails.rb
When `ActionMailer` is not defined we have empty `app/mailers/devise/mailer.rb` file and Zeitwerk doesn't like that and errors with
`expected file app/mailers/devise/mailer.rb to define constant Devise::Mailer`
The fix is to tell Zeitwerk to ignore that file if `ActionMailer` constant if not defined. 
I tried to write a spec for it but since specs are run in the same process it's hard to have two Rails applications where one of them has `ActionMailer` define and the seconds one doesn't.
closes #5140, #5485
> Fix Zeitwerk autoloading when ActionMailer is not present.

- lib/devise/rails/routes.rb
- test/routes_test.rb
closes https://github.com/heartcombo/devise/issues/5500 https://github.com/heartcombo/devise/issues/5689
> Fix passing of format option to devise_for call.

- CHANGELOG.md
- lib/devise/models/validatable.rb
- test/models_test.rb
This change is useful for instances where applications have the need to support dynamic password lengths, without a system restart. Such applications will just have to override the `password_length` method in their own classes to support dynamic password lengths.
Gitlab uses it like this:
```ruby
class User < ApplicationRecord
...
class << self
def password_length
Gitlab::CurrentSettings.minimum_password_length..Devise.password_length.max
end
end
end
```
> Use proc to set password length validator so it's possible to override it dynamically.
