test/controllers/custom_registrations_controller_test.rb
test/rails_app/app/controllers/custom/registrations_controller.rb

Tests the code added in 1bbcc54026d90731179a8f610ab26a437fa02fec

adding test for RegistrationsController#new yielding the resource

---

CHANGELOG.md
lib/devise/models/confirmable.rb
lib/devise/models/recoverable.rb
test/controllers/custom_registrations_controller_test.rb
test/controllers/passwords_controller_test.rb
test/controllers/sessions_controller_test.rb
test/models/confirmable_test.rb
test/models/lockable_test.rb
test/models/recoverable_test.rb
test/support/integration.rb
test/test_helpers_test.rb

Removes the bang in confirm! and reset_password!

---

lib/devise/failure_app.rb

Conditionally use flashes in failure_app

---

lib/generators/templates/controllers/registrations_controller.rb
lib/generators/templates/controllers/sessions_controller.rb

Fixes #3595.
Feedback welcome on the actual comment text.

Change comments on registration and session controller configure methods

---

README.md

Like discussed at the bottom of this ticket : https://github.com/plataformatec/devise/issues/1029

Adding link to wiki + include clarification

---

Rakefile

Tiding up according to general guidelines, let's be perfectionists. :)

Formatting

---

README.md

This will help beginners to get started with Rails/Devise frameworks with GoRails powered by One Month. I find this resource really useful to get started and it explains in depth on how and when to implement Devise in a short amount of time at the user's discretion.

Add GoRails resource into README.md

---

README.md

A really good , learn by doing, tutorial at codecademy

Add codecademy authorization tutorial

---

lib/devise/rails/routes.rb

Previous solution was too complex and wasn't worked for everyone. See discussion at #2227 for details
Fixes #3651

Provided another solution in error message when using omniauth callbacks under a dynamic segment

---

Gemfile

Hopefully this PR makes tests green again.

Just use regular 4.x mongoid gem

---

lib/devise/failure_app.rb

Only tested in my Rails 4.2.3 app

Fix infinite redirect in Rails 4.2 authenticated routes. Closes #3643

---

CHANGELOG.md

my app failed to start because the method was removed. I think it makes sense to mention it here.

Add removed method to CHANGELOG

---

lib/devise/models.rb

Minor comment fix to account for API refactoring

Update docs for Devise::Models.config

---

CHANGELOG.md
Gemfile.lock
app/mailers/devise/mailer.rb
app/views/devise/mailer/password_change.html.erb
config/locales/en.yml
lib/devise.rb
lib/devise/models/database_authenticatable.rb
lib/devise/version.rb
lib/generators/devise/views_generator.rb
lib/generators/templates/devise.rb
lib/generators/templates/markerb/password_change.markerb
test/generators/views_generator_test.rb
test/models/database_authenticatable_test.rb
test/models_test.rb
test/support/stub_model_filters.rb

Decided to give #3634 a shot as I had to do this manually recently. Comment or close as you see fit!
This sends an email to the user when password is altered nad an option to enable or disable password-changed notification (defaulted to false). 
Happy to alter as comments come in, just took a stab at it!

Add password change notification

---

lib/devise/models/recoverable.rb

`#reset_password` always saves the record if validation passes.

Remove outdated example from documentation

---

lib/devise/failure_app.rb
test/failure_app_test.rb

Account for relative_url_root in FailureApp's recall method

---

app/controllers/devise_controller.rb
test/controllers/helper_methods_test.rb

Solve #3864 using logic from #3732
includes wrapping `helper` & `helper_method` calls with `respond_to?` conditionals

Add #3732 helper logic to devise controller

---

README.md

Added the link to devise README.

Add link to devise_for documentation

---

lib/generators/devise/install_generator.rb
test/generators/install_generator_test.rb

This is my stab at fixing #3800. I'm happy to keep working on this if you have feedback, I've used Devise on many projects and figured I would try and do my part to contribute.
Thanks!
Arjun

Raise error if no ORM is found during install generator

---

README.md

[A change in Rails 5](https://github.com/rails/rails/commit/39794037817703575c35a75f1961b01b83791191) left me hunting for hours on why I could no longer log in to my application. To save others the trouble, I thought it would be nice to note it in the README.

Note change to Rails 5 that affects Devise example

---

lib/generators/devise/orm_helpers.rb
test/rails_app/config/boot.rb

method File::exists? is deprecated.

fix method name for File

---

gemfiles/Gemfile.rails-5.0-beta.lock
test/rails_app/app/active_record/user.rb

With this [PR](https://github.com/rails/activemodel-serializers-xml/pull/8)
of activemodel-serializers bundler will require it by default.

Fix Rails 5 build

---

app/controllers/devise/registrations_controller.rb
app/views/devise/registrations/edit.html.erb
test/integration/registerable_test.rb

Set minimum password length for edit and new views

---

lib/devise/models/authenticatable.rb

Hello,
Just found out that the example of the original method is not 100% the same, so proposing to keep in sync. Not sure if the comment should be there either. Please let me know. Thanks.

Update example code in authenticatable model

---

guides/bug_report_templates/integration_test_master.rb

Hello guys,
as related on #3958 , this PR add to project, a executable test script to help with devise issues,
I added it to guides folder (rails uses this structure) please let me know if you guys wanna I change it.
Also, I saw you guys has the steps to report a bug on wiki,  let me know if should I update it as well (I think after the accept PR)
also, as suggests @ulissesalmeida I did changes on script, instead uses `ActionController::TestCase`, now it's using `ActionDispatch::IntegrationTest`.
Thanks,

fix #3958 adding helper test to report bugs

---

lib/devise/rails/routes.rb

Fix small typo

---

README.md

Updates url for omniauth to omniauth/omniauth repo

---

lib/devise/failure_app.rb

Just noticed these while reading them today, thought they could be slightly improved.

Fix typos in failure_app comments

---

README.md

For me it was necessary to stop spring for the route helpers to be defined.

added note about stopping spring

---

README.md

Though there is a link to friendly navigable format to this doc, I think it's hard to find/notice. Also, I think it would be much helpful to have TOC on the readme, as it is getting hefty.

Adds Table of content to Readme.md

---

lib/devise/models/validatable.rb

lib/generators/templates/devise.rb#L160

change validatable docs to match generator

---

app/views/devise/confirmations/new.html.erb
app/views/devise/passwords/new.html.erb
app/views/devise/registrations/edit.html.erb
app/views/devise/registrations/new.html.erb
app/views/devise/sessions/new.html.erb
app/views/devise/unlocks/new.html.erb

As discussed in https://github.com/plataformatec/devise/issues/4635

Adding `autocomplete="email"` to email fields

---

lib/generators/active_record/devise_generator.rb
lib/generators/devise/orm_helpers.rb
test/generators/active_record_generator_test.rb

Added the ability to change the default migrations path (introduced in Rails 5.0.3)
Please see:
https://github.com/rails/rails/commit/8ca3de2eb37e87243d4141610068920b3c0abdc8#diff-b3e4617f47cb06d8e22542a2c2e40d97

Added the ability to change the default migrations path

---

devise.gemspec

Fixes https://github.com/bundler/bundler/issues/6220

[Gemspec] Ensure it is loaded as utf-8

---

lib/devise/controllers/helpers.rb
test/integration/authenticatable_test.rb

Reverts plataformatec/devise#4375
See https://github.com/plataformatec/devise/pull/4788#issuecomment-373162124 for more information.

Revert "Replace log_process_action to append_info_to_payload"

---

lib/devise/models/database_authenticatable.rb

- refactor `update_with_password` method and `destroy_with_password` method.

Remove redundant self from database_authenticatable module.

---

CHANGELOG.md
lib/generators/templates/simple_form_for/confirmations/new.html.erb
lib/generators/templates/simple_form_for/passwords/edit.html.erb
lib/generators/templates/simple_form_for/passwords/new.html.erb
lib/generators/templates/simple_form_for/registrations/edit.html.erb
lib/generators/templates/simple_form_for/registrations/new.html.erb
lib/generators/templates/simple_form_for/sessions/new.html.erb
lib/generators/templates/simple_form_for/unlocks/new.html.erb

Update `simple_form` templates with changes from 16b3d6d67c7e017d461ea17ed29ea9738dc77e83 and 6260c29a867b9a656f1e1557abe347a523178fab

Update simple form templates

---

app/controllers/devise/passwords_controller.rb
test/controllers/passwords_controller_test.rb

[#4841] Add `after_database_authentication` callback after sign_in immediately after password update

---

app/views/devise/sessions/new.html.erb

I noticed two extra characters, in my opinion they should not be there.

Removed extra characters

---

lib/generators/templates/simple_form_for/registrations/new.html.erb

Signed-off-by: samslow <shsvkdldj@likelion.org>
white space removed
If it is intended, please refuse.

removing white space in devise generator new.html.erb

---

README.md

Adds a section to help contributors run Devise test suite.

Update README to help run tests [ci skip]

---

README.md

Added mention of API mode complications to README

---

lib/devise/failure_app.rb

Fix rails_51_and_up? method for Rails 6.rc1

---

config/locales/en.yml

This PR just fix the typo in the message for email update :)

Fix typo in email update message

---

lib/generators/templates/devise.rb
test/rails_app/config/initializers/devise.rb

Explain layout of default config initializer

---

lib/generators/templates/devise.rb

I could not find documentation about what happens if you change stretches.

Explain how changing stretches affects existing password hashes

---

README.md

Updated README.md with the latest link to Ryan Bates' Railscast

Update README.md with the current link to Ryan Bates' Railscast

---

README.md

I'm preparing an episode on Drifting Ruby to demonstrate on how to contribute to a gem, so I made this small PR; adding a resource of information into the README.

Updated README with additional video resources for learning Devise

---

lib/devise/test/controller_helpers.rb
test/rails_app/app/controllers/streaming_controller.rb
test/rails_app/config/routes.rb
test/test/controller_helpers_test.rb

Fix hanging tests for streaming controllers using Devise

---

lib/devise/models/lockable.rb

[Documentation  Minor Typo] - Update lockable.rb
